/* ----------------------------------------------------------------------
   A1 GERMAN VOCABULARY DATA
   [de, article|null, pos, en(string|array), category]
------------------------------------------------------------------------*/
const RAW = [
  // Greetings & phrases
  ["Hallo", null, "phrase", "hello", "greetings"],
  ["Guten Morgen", null, "phrase", "good morning", "greetings"],
  ["Guten Tag", null, "phrase", "good day", "greetings"],
  ["Guten Abend", null, "phrase", "good evening", "greetings"],
  ["Gute Nacht", null, "phrase", "good night", "greetings"],
  ["Auf Wiedersehen", null, "phrase", "goodbye", "greetings"],
  ["Tschüss", null, "phrase", "bye", "greetings"],
  ["Bis bald", null, "phrase", "see you soon", "greetings"],
  ["Bitte", null, "phrase", ["please", "you're welcome"], "greetings"],
  ["Danke", null, "phrase", "thank you", "greetings"],
  ["Entschuldigung", null, "phrase", ["excuse me", "sorry"], "greetings"],
  ["Ja", null, "phrase", "yes", "greetings"],
  ["Nein", null, "phrase", "no", "greetings"],
  ["Vielleicht", null, "adv", "maybe", "greetings"],
  ["Wie geht es dir", null, "phrase", "how are you", "greetings"],
  ["Mir geht es gut", null, "phrase", "I'm fine", "greetings"],
  ["Willkommen", null, "phrase", "welcome", "greetings"],

  // Pronouns
  ["ich", null, "pron", "I", "pronouns"],
  ["du", null, "pron", "you", "pronouns"],
  ["er", null, "pron", "he", "pronouns"],
  ["sie", null, "pron", "she", "pronouns"],
  ["es", null, "pron", "it", "pronouns"],
  ["wir", null, "pron", "we", "pronouns"],
  ["ihr", null, "pron", "you (plural)", "pronouns"],
  ["mein", null, "pron", "my", "pronouns"],
  ["dein", null, "pron", "your", "pronouns"],
  ["sein", null, "pron", "his", "pronouns"],
  ["unser", null, "pron", "our", "pronouns"],

  // Question words
  ["wer", null, "pron", "who", "questions"],
  ["was", null, "pron", "what", "questions"],
  ["wo", null, "adv", "where", "questions"],
  ["wann", null, "adv", "when", "questions"],
  ["warum", null, "adv", "why", "questions"],
  ["wie", null, "adv", "how", "questions"],
  ["welche", null, "pron", "which", "questions"],

  // Numbers
  ["null", null, "num", "zero", "numbers"],
  ["eins", null, "num", "one", "numbers"],
  ["zwei", null, "num", "two", "numbers"],
  ["drei", null, "num", "three", "numbers"],
  ["vier", null, "num", "four", "numbers"],
  ["fünf", null, "num", "five", "numbers"],
  ["sechs", null, "num", "six", "numbers"],
  ["sieben", null, "num", "seven", "numbers"],
  ["acht", null, "num", "eight", "numbers"],
  ["neun", null, "num", "nine", "numbers"],
  ["zehn", null, "num", "ten", "numbers"],
  ["elf", null, "num", "eleven", "numbers"],
  ["zwölf", null, "num", "twelve", "numbers"],
  ["dreizehn", null, "num", "thirteen", "numbers"],
  ["vierzehn", null, "num", "fourteen", "numbers"],
  ["fünfzehn", null, "num", "fifteen", "numbers"],
  ["zwanzig", null, "num", "twenty", "numbers"],
  ["dreißig", null, "num", "thirty", "numbers"],
  ["vierzig", null, "num", "forty", "numbers"],
  ["fünfzig", null, "num", "fifty", "numbers"],
  ["hundert", null, "num", "hundred", "numbers"],
  ["tausend", null, "num", "thousand", "numbers"],

  // Colors
  ["rot", null, "adj", "red", "colors"],
  ["blau", null, "adj", "blue", "colors"],
  ["gelb", null, "adj", "yellow", "colors"],
  ["grün", null, "adj", "green", "colors"],
  ["schwarz", null, "adj", "black", "colors"],
  ["weiß", null, "adj", "white", "colors"],
  ["braun", null, "adj", "brown", "colors"],
  ["orange", null, "adj", "orange", "colors"],
  ["rosa", null, "adj", "pink", "colors"],
  ["grau", null, "adj", "grey", "colors"],
  ["lila", null, "adj", "purple", "colors"],

  // Family
  ["Familie", "die", "n", "family", "family"],
  ["Mutter", "die", "n", "mother", "family"],
  ["Vater", "der", "n", "father", "family"],
  ["Schwester", "die", "n", "sister", "family"],
  ["Bruder", "der", "n", "brother", "family"],
  ["Tochter", "die", "n", "daughter", "family"],
  ["Sohn", "der", "n", "son", "family"],
  ["Großmutter", "die", "n", "grandmother", "family"],
  ["Großvater", "der", "n", "grandfather", "family"],
  ["Frau", "die", "n", ["woman", "wife"], "family"],
  ["Mann", "der", "n", ["man", "husband"], "family"],
  ["Kind", "das", "n", "child", "family"],
  ["Eltern", "die", "n", "parents", "family"],
  ["Tante", "die", "n", "aunt", "family"],
  ["Onkel", "der", "n", "uncle", "family"],
  ["Freund", "der", "n", ["friend", "boyfriend"], "family"],
  ["Freundin", "die", "n", ["friend", "girlfriend"], "family"],

  // Food & drink
  ["Brot", "das", "n", "bread", "food"],
  ["Käse", "der", "n", "cheese", "food"],
  ["Milch", "die", "n", "milk", "food"],
  ["Wasser", "das", "n", "water", "food"],
  ["Kaffee", "der", "n", "coffee", "food"],
  ["Tee", "der", "n", "tea", "food"],
  ["Apfel", "der", "n", "apple", "food"],
  ["Banane", "die", "n", "banana", "food"],
  ["Ei", "das", "n", "egg", "food"],
  ["Zucker", "der", "n", "sugar", "food"],
  ["Salz", "das", "n", "salt", "food"],
  ["Suppe", "die", "n", "soup", "food"],
  ["Fleisch", "das", "n", "meat", "food"],
  ["Fisch", "der", "n", "fish", "food"],
  ["Gemüse", "das", "n", "vegetables", "food"],
  ["Reis", "der", "n", "rice", "food"],
  ["Kartoffel", "die", "n", "potato", "food"],
  ["Saft", "der", "n", "juice", "food"],
  ["Wein", "der", "n", "wine", "food"],
  ["Bier", "das", "n", "beer", "food"],
  ["Frühstück", "das", "n", "breakfast", "food"],
  ["Mittagessen", "das", "n", "lunch", "food"],
  ["Abendessen", "das", "n", "dinner", "food"],
  ["Kuchen", "der", "n", "cake", "food"],
  ["Schokolade", "die", "n", "chocolate", "food"],

  // Time & calendar
  ["Zeit", "die", "n", "time", "time"],
  ["Stunde", "die", "n", "hour", "time"],
  ["Minute", "die", "n", "minute", "time"],
  ["Tag", "der", "n", "day", "time"],
  ["Woche", "die", "n", "week", "time"],
  ["Monat", "der", "n", "month", "time"],
  ["Jahr", "das", "n", "year", "time"],
  ["heute", null, "adv", "today", "time"],
  ["morgen", null, "adv", "tomorrow", "time"],
  ["gestern", null, "adv", "yesterday", "time"],
  ["Montag", "der", "n", "Monday", "time"],
  ["Dienstag", "der", "n", "Tuesday", "time"],
  ["Mittwoch", "der", "n", "Wednesday", "time"],
  ["Donnerstag", "der", "n", "Thursday", "time"],
  ["Freitag", "der", "n", "Friday", "time"],
  ["Samstag", "der", "n", "Saturday", "time"],
  ["Sonntag", "der", "n", "Sunday", "time"],
  ["Januar", "der", "n", "January", "time"],
  ["Februar", "der", "n", "February", "time"],
  ["März", "der", "n", "March", "time"],
  ["April", "der", "n", "April", "time"],
  ["Mai", "der", "n", "May", "time"],
  ["Juni", "der", "n", "June", "time"],
  ["Juli", "der", "n", "July", "time"],
  ["August", "der", "n", "August", "time"],
  ["September", "der", "n", "September", "time"],
  ["Oktober", "der", "n", "October", "time"],
  ["November", "der", "n", "November", "time"],
  ["Dezember", "der", "n", "December", "time"],
  ["Frühling", "der", "n", "spring", "time"],
  ["Sommer", "der", "n", "summer", "time"],
  ["Herbst", "der", "n", "autumn", "time"],
  ["Winter", "der", "n", "winter", "time"],

  // Weather
  ["Wetter", "das", "n", "weather", "weather"],
  ["Sonne", "die", "n", "sun", "weather"],
  ["Regen", "der", "n", "rain", "weather"],
  ["Schnee", "der", "n", "snow", "weather"],
  ["Wind", "der", "n", "wind", "weather"],
  ["warm", null, "adj", "warm", "weather"],
  ["kalt", null, "adj", "cold", "weather"],
  ["heiß", null, "adj", "hot", "weather"],
  ["kühl", null, "adj", "cool", "weather"],

  // Body
  ["Kopf", "der", "n", "head", "body"],
  ["Auge", "das", "n", "eye", "body"],
  ["Nase", "die", "n", "nose", "body"],
  ["Mund", "der", "n", "mouth", "body"],
  ["Ohr", "das", "n", "ear", "body"],
  ["Hand", "die", "n", "hand", "body"],
  ["Fuß", "der", "n", "foot", "body"],
  ["Arm", "der", "n", "arm", "body"],
  ["Bein", "das", "n", "leg", "body"],
  ["Bauch", "der", "n", "stomach", "body"],
  ["Haar", "das", "n", "hair", "body"],
  ["Rücken", "der", "n", "back", "body"],

  // Clothing
  ["Kleidung", "die", "n", "clothing", "clothing"],
  ["Hemd", "das", "n", "shirt", "clothing"],
  ["Hose", "die", "n", "trousers", "clothing"],
  ["Rock", "der", "n", "skirt", "clothing"],
  ["Kleid", "das", "n", "dress", "clothing"],
  ["Jacke", "die", "n", "jacket", "clothing"],
  ["Schuhe", "die", "n", "shoes", "clothing"],
  ["Hut", "der", "n", "hat", "clothing"],
  ["Mütze", "die", "n", "cap", "clothing"],

  // House
  ["Haus", "das", "n", "house", "house"],
  ["Wohnung", "die", "n", "apartment", "house"],
  ["Zimmer", "das", "n", "room", "house"],
  ["Küche", "die", "n", "kitchen", "house"],
  ["Bad", "das", "n", "bathroom", "house"],
  ["Schlafzimmer", "das", "n", "bedroom", "house"],
  ["Wohnzimmer", "das", "n", "living room", "house"],
  ["Tisch", "der", "n", "table", "house"],
  ["Stuhl", "der", "n", "chair", "house"],
  ["Bett", "das", "n", "bed", "house"],
  ["Tür", "die", "n", "door", "house"],
  ["Fenster", "das", "n", "window", "house"],
  ["Wand", "die", "n", "wall", "house"],
  ["Boden", "der", "n", "floor", "house"],
  ["Lampe", "die", "n", "lamp", "house"],

  // Places
  ["Stadt", "die", "n", "city", "places"],
  ["Dorf", "das", "n", "village", "places"],
  ["Straße", "die", "n", "street", "places"],
  ["Park", "der", "n", "park", "places"],
  ["Schule", "die", "n", "school", "places"],
  ["Universität", "die", "n", "university", "places"],
  ["Krankenhaus", "das", "n", "hospital", "places"],
  ["Bahnhof", "der", "n", "train station", "places"],
  ["Flughafen", "der", "n", "airport", "places"],
  ["Geschäft", "das", "n", "shop", "places"],
  ["Supermarkt", "der", "n", "supermarket", "places"],
  ["Restaurant", "das", "n", "restaurant", "places"],
  ["Hotel", "das", "n", "hotel", "places"],
  ["Kirche", "die", "n", "church", "places"],
  ["Bibliothek", "die", "n", "library", "places"],
  ["Büro", "das", "n", "office", "places"],
  ["Markt", "der", "n", "market", "places"],

  // Transport
  ["Auto", "das", "n", "car", "transport"],
  ["Bus", "der", "n", "bus", "transport"],
  ["Zug", "der", "n", "train", "transport"],
  ["Fahrrad", "das", "n", "bicycle", "transport"],
  ["Flugzeug", "das", "n", "airplane", "transport"],
  ["Schiff", "das", "n", "ship", "transport"],
  ["U-Bahn", "die", "n", "subway", "transport"],
  ["Taxi", "das", "n", "taxi", "transport"],

  // Verbs
  ["sein", null, "v", ["to be", "be"], "verbs"],
  ["haben", null, "v", ["to have", "have"], "verbs"],
  ["werden", null, "v", ["to become", "become"], "verbs"],
  ["gehen", null, "v", ["to go", "go"], "verbs"],
  ["kommen", null, "v", ["to come", "come"], "verbs"],
  ["machen", null, "v", ["to make", "to do", "do"], "verbs"],
  ["sagen", null, "v", ["to say", "say"], "verbs"],
  ["sehen", null, "v", ["to see", "see"], "verbs"],
  ["wissen", null, "v", ["to know", "know"], "verbs"],
  ["geben", null, "v", ["to give", "give"], "verbs"],
  ["nehmen", null, "v", ["to take", "take"], "verbs"],
  ["finden", null, "v", ["to find", "find"], "verbs"],
  ["denken", null, "v", ["to think", "think"], "verbs"],
  ["bleiben", null, "v", ["to stay", "stay"], "verbs"],
  ["liegen", null, "v", ["to lie", "lie down"], "verbs"],
  ["sitzen", null, "v", ["to sit", "sit"], "verbs"],
  ["stehen", null, "v", ["to stand", "stand"], "verbs"],
  ["arbeiten", null, "v", ["to work", "work"], "verbs"],
  ["spielen", null, "v", ["to play", "play"], "verbs"],
  ["lernen", null, "v", ["to learn", "learn"], "verbs"],
  ["essen", null, "v", ["to eat", "eat"], "verbs"],
  ["trinken", null, "v", ["to drink", "drink"], "verbs"],
  ["schlafen", null, "v", ["to sleep", "sleep"], "verbs"],
  ["leben", null, "v", ["to live", "live"], "verbs"],
  ["lieben", null, "v", ["to love", "love"], "verbs"],
  ["mögen", null, "v", ["to like", "like"], "verbs"],
  ["brauchen", null, "v", ["to need", "need"], "verbs"],
  ["kaufen", null, "v", ["to buy", "buy"], "verbs"],
  ["verkaufen", null, "v", ["to sell", "sell"], "verbs"],
  ["kochen", null, "v", ["to cook", "cook"], "verbs"],
  ["lesen", null, "v", ["to read", "read"], "verbs"],
  ["schreiben", null, "v", ["to write", "write"], "verbs"],
  ["sprechen", null, "v", ["to speak", "speak"], "verbs"],
  ["hören", null, "v", ["to hear", "to listen", "listen"], "verbs"],
  ["fragen", null, "v", ["to ask", "ask"], "verbs"],
  ["antworten", null, "v", ["to answer", "answer"], "verbs"],
  ["helfen", null, "v", ["to help", "help"], "verbs"],
  ["verstehen", null, "v", ["to understand", "understand"], "verbs"],
  ["fahren", null, "v", ["to drive", "to go (by vehicle)", "drive"], "verbs"],
  ["fliegen", null, "v", ["to fly", "fly"], "verbs"],
  ["laufen", null, "v", ["to run", "to walk", "run"], "verbs"],
  ["tanzen", null, "v", ["to dance", "dance"], "verbs"],
  ["singen", null, "v", ["to sing", "sing"], "verbs"],
  ["kennen", null, "v", ["to know", "to be familiar with", "know"], "verbs"],
  ["wohnen", null, "v", ["to live", "to reside", "reside"], "verbs"],
  ["heißen", null, "v", ["to be called", "be named"], "verbs"],
  ["öffnen", null, "v", ["to open", "open"], "verbs"],
  ["schließen", null, "v", ["to close", "close"], "verbs"],
  ["warten", null, "v", ["to wait", "wait"], "verbs"],

  // Adjectives
  ["groß", null, "adj", ["big", "tall"], "adjectives"],
  ["klein", null, "adj", "small", "adjectives"],
  ["gut", null, "adj", "good", "adjectives"],
  ["schlecht", null, "adj", "bad", "adjectives"],
  ["neu", null, "adj", "new", "adjectives"],
  ["alt", null, "adj", "old", "adjectives"],
  ["jung", null, "adj", "young", "adjectives"],
  ["schön", null, "adj", ["beautiful", "nice"], "adjectives"],
  ["hässlich", null, "adj", "ugly", "adjectives"],
  ["schnell", null, "adj", "fast", "adjectives"],
  ["langsam", null, "adj", "slow", "adjectives"],
  ["leicht", null, "adj", ["easy", "light"], "adjectives"],
  ["schwer", null, "adj", ["difficult", "heavy"], "adjectives"],
  ["teuer", null, "adj", "expensive", "adjectives"],
  ["billig", null, "adj", "cheap", "adjectives"],
  ["glücklich", null, "adj", "happy", "adjectives"],
  ["traurig", null, "adj", "sad", "adjectives"],
  ["müde", null, "adj", "tired", "adjectives"],
  ["hungrig", null, "adj", "hungry", "adjectives"],
  ["durstig", null, "adj", "thirsty", "adjectives"],
  ["sauber", null, "adj", "clean", "adjectives"],
  ["schmutzig", null, "adj", "dirty", "adjectives"],
  ["laut", null, "adj", "loud", "adjectives"],
  ["leise", null, "adj", "quiet", "adjectives"],
  ["wichtig", null, "adj", "important", "adjectives"],
  ["richtig", null, "adj", "correct", "adjectives"],
  ["falsch", null, "adj", "wrong", "adjectives"],
  ["voll", null, "adj", "full", "adjectives"],
  ["leer", null, "adj", "empty", "adjectives"],
  ["offen", null, "adj", "open", "adjectives"],
  ["geschlossen", null, "adj", "closed", "adjectives"],

  // Prepositions & conjunctions
  ["in", null, "prep", "in", "grammar"],
  ["auf", null, "prep", "on", "grammar"],
  ["unter", null, "prep", "under", "grammar"],
  ["über", null, "prep", "over", "grammar"],
  ["neben", null, "prep", "next to", "grammar"],
  ["vor", null, "prep", ["in front of", "before"], "grammar"],
  ["hinter", null, "prep", "behind", "grammar"],
  ["zwischen", null, "prep", "between", "grammar"],
  ["mit", null, "prep", "with", "grammar"],
  ["ohne", null, "prep", "without", "grammar"],
  ["für", null, "prep", "for", "grammar"],
  ["gegen", null, "prep", "against", "grammar"],
  ["und", null, "conj", "and", "grammar"],
  ["oder", null, "conj", "or", "grammar"],
  ["aber", null, "conj", "but", "grammar"],
  ["weil", null, "conj", "because", "grammar"],
  ["dass", null, "conj", "that", "grammar"],
  ["wenn", null, "conj", "if", "grammar"],

  // Misc nouns
  ["Name", "der", "n", "name", "misc"],
  ["Adresse", "die", "n", "address", "misc"],
  ["Telefonnummer", "die", "n", "phone number", "misc"],
  ["Arbeit", "die", "n", "work", "misc"],
  ["Beruf", "der", "n", "job", "misc"],
  ["Geld", "das", "n", "money", "misc"],
  ["Zeitung", "die", "n", "newspaper", "misc"],
  ["Buch", "das", "n", "book", "misc"],
  ["Stift", "der", "n", "pen", "misc"],
  ["Papier", "das", "n", "paper", "misc"],
  ["Tasche", "die", "n", "bag", "misc"],
  ["Schlüssel", "der", "n", "key", "misc"],
  ["Handy", "das", "n", "mobile phone", "misc"],
  ["Computer", "der", "n", "computer", "misc"],
  ["Foto", "das", "n", "photo", "misc"],
  ["Musik", "die", "n", "music", "misc"],
  ["Film", "der", "n", "film", "misc"],
  ["Spiel", "das", "n", "game", "misc"],
  ["Sprache", "die", "n", "language", "misc"],
  ["Welt", "die", "n", "world", "misc"],

  // Numbers & ordinals (extra)
  ["sechzehn", null, "num", "sixteen", "numbers"],
  ["siebzehn", null, "num", "seventeen", "numbers"],
  ["achtzehn", null, "num", "eighteen", "numbers"],
  ["neunzehn", null, "num", "nineteen", "numbers"],
  ["sechzig", null, "num", "sixty", "numbers"],
  ["siebzig", null, "num", "seventy", "numbers"],
  ["achtzig", null, "num", "eighty", "numbers"],
  ["neunzig", null, "num", "ninety", "numbers"],
  ["erste", null, "num", "first", "numbers"],
  ["zweite", null, "num", "second", "numbers"],
  ["dritte", null, "num", "third", "numbers"],
  ["letzte", null, "num", "last", "numbers"],
  ["Million", "die", "n", "million", "numbers"],
  ["Nummer", "die", "n", "number", "numbers"],

  // Time (extra)
  ["Uhr", "die", "n", ["o'clock", "clock"], "time"],
  ["Mittag", "der", "n", "midday", "time"],
  ["Mitternacht", "die", "n", "midnight", "time"],
  ["Vormittag", "der", "n", "late morning", "time"],
  ["Nachmittag", "der", "n", "afternoon", "time"],
  ["Wochenende", "das", "n", "weekend", "time"],
  ["Feiertag", "der", "n", "public holiday", "time"],

  // Directions
  ["links", null, "adv", "left", "directions"],
  ["rechts", null, "adv", "right", "directions"],
  ["geradeaus", null, "adv", "straight ahead", "directions"],
  ["oben", null, "adv", ["above", "upstairs"], "directions"],
  ["unten", null, "adv", ["below", "downstairs"], "directions"],
  ["hier", null, "adv", "here", "directions"],
  ["dort", null, "adv", "there", "directions"],

  // Adverbs & quantifiers
  ["auch", null, "adv", "also", "adverbs"],
  ["sehr", null, "adv", "very", "adverbs"],
  ["immer", null, "adv", "always", "adverbs"],
  ["nie", null, "adv", "never", "adverbs"],
  ["schon", null, "adv", "already", "adverbs"],
  ["noch", null, "adv", "still", "adverbs"],
  ["jetzt", null, "adv", "now", "adverbs"],
  ["später", null, "adv", "later", "adverbs"],
  ["früher", null, "adv", "earlier", "adverbs"],
  ["zusammen", null, "adv", "together", "adverbs"],
  ["allein", null, "adv", "alone", "adverbs"],
  ["wieder", null, "adv", "again", "adverbs"],
  ["nur", null, "adv", "only", "adverbs"],
  ["fast", null, "adv", "almost", "adverbs"],
  ["genau", null, "adv", "exactly", "adverbs"],
  ["wirklich", null, "adv", "really", "adverbs"],
  ["natürlich", null, "adv", "naturally", "adverbs"],
  ["leider", null, "adv", "unfortunately", "adverbs"],
  ["gern", null, "adv", "gladly", "adverbs"],
  ["oft", null, "adv", "often", "adverbs"],
  ["manchmal", null, "adv", "sometimes", "adverbs"],
  ["etwas", null, "pron", "something", "adverbs"],
  ["nichts", null, "pron", "nothing", "adverbs"],
  ["alles", null, "pron", "everything", "adverbs"],

  // Modal verbs
  ["können", null, "v", ["can", "to be able to"], "verbs"],
  ["müssen", null, "v", ["must", "to have to"], "verbs"],
  ["dürfen", null, "v", ["may", "to be allowed to"], "verbs"],
  ["sollen", null, "v", ["should", "to be supposed to"], "verbs"],
  ["wollen", null, "v", ["to want", "want"], "verbs"],
  ["möchten", null, "v", ["would like", "want"], "verbs"],

  // More verbs
  ["anfangen", null, "v", ["to begin", "begin"], "verbs"],
  ["aufhören", null, "v", ["to stop", "stop"], "verbs"],
  ["bezahlen", null, "v", ["to pay", "pay"], "verbs"],
  ["bestellen", null, "v", ["to order", "order"], "verbs"],
  ["packen", null, "v", ["to pack", "pack"], "verbs"],
  ["waschen", null, "v", ["to wash", "wash"], "verbs"],
  ["putzen", null, "v", ["to clean", "clean"], "verbs"],
  ["aufräumen", null, "v", ["to tidy up", "tidy up"], "verbs"],
  ["einkaufen", null, "v", ["to shop", "shop"], "verbs"],
  ["umziehen", null, "v", ["to move house", "move house"], "verbs"],
  ["besuchen", null, "v", ["to visit", "visit"], "verbs"],
  ["treffen", null, "v", ["to meet", "meet"], "verbs"],
  ["zeigen", null, "v", ["to show", "show"], "verbs"],
  ["bringen", null, "v", ["to bring", "bring"], "verbs"],
  ["holen", null, "v", ["to fetch", "fetch"], "verbs"],
  ["schicken", null, "v", ["to send", "send"], "verbs"],
  ["bekommen", null, "v", ["to receive", "get"], "verbs"],
  ["versuchen", null, "v", ["to try", "try"], "verbs"],
  ["erklären", null, "v", ["to explain", "explain"], "verbs"],
  ["vergessen", null, "v", ["to forget", "forget"], "verbs"],
  ["weinen", null, "v", ["to cry", "cry"], "verbs"],
  ["lachen", null, "v", ["to laugh", "laugh"], "verbs"],
  ["duschen", null, "v", ["to shower", "shower"], "verbs"],
  ["aufwachen", null, "v", ["to wake up", "wake up"], "verbs"],
  ["aufstehen", null, "v", ["to get up", "get up"], "verbs"],
  ["reisen", null, "v", ["to travel", "travel"], "verbs"],
  ["fotografieren", null, "v", ["to photograph", "take photos"], "verbs"],

  // More adjectives
  ["interessant", null, "adj", "interesting", "adjectives"],
  ["langweilig", null, "adj", "boring", "adjectives"],
  ["freundlich", null, "adj", "friendly", "adjectives"],
  ["nett", null, "adj", "nice", "adjectives"],
  ["lustig", null, "adj", "funny", "adjectives"],
  ["ruhig", null, "adj", "calm", "adjectives"],
  ["nervös", null, "adj", "nervous", "adjectives"],
  ["krank", null, "adj", "sick", "adjectives"],
  ["gesund", null, "adj", "healthy", "adjectives"],
  ["stark", null, "adj", "strong", "adjectives"],
  ["schwach", null, "adj", "weak", "adjectives"],
  ["hell", null, "adj", "bright", "adjectives"],
  ["dunkel", null, "adj", "dark", "adjectives"],
  ["modern", null, "adj", "modern", "adjectives"],
  ["bequem", null, "adj", "comfortable", "adjectives"],
  ["frei", null, "adj", "free", "adjectives"],
  ["sicher", null, "adj", "safe", "adjectives"],
  ["gefährlich", null, "adj", "dangerous", "adjectives"],
  ["einfach", null, "adj", "simple", "adjectives"],
  ["kompliziert", null, "adj", "complicated", "adjectives"],
  ["gleich", null, "adj", "same", "adjectives"],
  ["fertig", null, "adj", "finished", "adjectives"],
  ["kaputt", null, "adj", "broken", "adjectives"],
  ["frisch", null, "adj", "fresh", "adjectives"],

  // Animals
  ["Hund", "der", "n", "dog", "animals"],
  ["Katze", "die", "n", "cat", "animals"],
  ["Vogel", "der", "n", "bird", "animals"],
  ["Pferd", "das", "n", "horse", "animals"],
  ["Kuh", "die", "n", "cow", "animals"],
  ["Schwein", "das", "n", "pig", "animals"],
  ["Huhn", "das", "n", "chicken", "animals"],
  ["Maus", "die", "n", "mouse", "animals"],

  // Hobbies & leisure
  ["Sport", "der", "n", "sport", "hobbies"],
  ["Fußball", "der", "n", ["football", "soccer"], "hobbies"],
  ["Kino", "das", "n", "cinema", "hobbies"],
  ["Theater", "das", "n", "theatre", "hobbies"],
  ["Ferien", "die", "n", "school holidays", "hobbies"],
  ["Urlaub", "der", "n", "vacation", "hobbies"],
  ["Reise", "die", "n", "trip", "hobbies"],
  ["Hobby", "das", "n", "hobby", "hobbies"],
  ["schwimmen", null, "v", ["to swim", "swim"], "hobbies"],
  ["malen", null, "v", ["to paint", "paint"], "hobbies"],

  // More house/rooms
  ["Toilette", "die", "n", "toilet", "house"],
  ["Garten", "der", "n", "garden", "house"],
  ["Keller", "der", "n", "cellar", "house"],
  ["Balkon", "der", "n", "balcony", "house"],
  ["Garage", "die", "n", "garage", "house"],
  ["Treppe", "die", "n", "stairs", "house"],
  ["Dach", "das", "n", "roof", "house"],

  // More clothing
  ["Socken", "die", "n", "socks", "clothing"],
  ["Handschuhe", "die", "n", "gloves", "clothing"],
  ["Schal", "der", "n", "scarf", "clothing"],
  ["Gürtel", "der", "n", "belt", "clothing"],
  ["Brille", "die", "n", "glasses", "clothing"],
  ["Pullover", "der", "n", "sweater", "clothing"],

  // More body
  ["Zahn", "der", "n", "tooth", "body"],
  ["Finger", "der", "n", "finger", "body"],
  ["Herz", "das", "n", "heart", "body"],
  ["Haut", "die", "n", "skin", "body"],
  ["Knie", "das", "n", "knee", "body"],

  // More transport
  ["Motorrad", "das", "n", "motorcycle", "transport"],
  ["Straßenbahn", "die", "n", "tram", "transport"],
  ["Fahrkarte", "die", "n", "ticket", "transport"],
  ["Haltestelle", "die", "n", ["bus stop", "stop"], "transport"],
  ["Gleis", "das", "n", ["platform", "track"], "transport"],

  // More places
  ["Post", "die", "n", "post office", "places"],
  ["Bank", "die", "n", "bank", "places"],
  ["Apotheke", "die", "n", "pharmacy", "places"],
  ["Tankstelle", "die", "n", "gas station", "places"],
  ["Friseur", "der", "n", "hairdresser", "places"],
  ["Zoo", "der", "n", "zoo", "places"],
  ["Strand", "der", "n", "beach", "places"],
  ["Berg", "der", "n", "mountain", "places"],
  ["Wald", "der", "n", "forest", "places"],
  ["See", "der", "n", "lake", "places"],
  ["Fluss", "der", "n", "river", "places"],
  ["Meer", "das", "n", "sea", "places"],

  // More everyday things
  ["Idee", "die", "n", "idea", "misc"],
  ["Frage", "die", "n", "question", "misc"],
  ["Antwort", "die", "n", "answer", "misc"],
  ["Problem", "das", "n", "problem", "misc"],
  ["Grund", "der", "n", "reason", "misc"],
  ["Beispiel", "das", "n", "example", "misc"],
  ["Nachricht", "die", "n", "message", "misc"],
  ["Brief", "der", "n", "letter", "misc"],
  ["E-Mail", "die", "n", "email", "misc"],
  ["Internet", "das", "n", "internet", "misc"],
  ["Passwort", "das", "n", "password", "misc"],
  ["Rechnung", "die", "n", ["bill", "invoice"], "misc"],
  ["Preis", "der", "n", "price", "misc"],
  ["Farbe", "die", "n", "color", "misc"],
  ["Plan", "der", "n", "plan", "misc"],

  // More food & drink
  ["Butter", "die", "n", "butter", "food"],
  ["Honig", "der", "n", "honey", "food"],
  ["Marmelade", "die", "n", "jam", "food"],
  ["Nudeln", "die", "n", ["pasta", "noodles"], "food"],
  ["Pizza", "die", "n", "pizza", "food"],
  ["Salat", "der", "n", "salad", "food"],
  ["Pfeffer", "der", "n", "pepper", "food"],
  ["Obst", "das", "n", "fruit", "food"],
  ["Orange", "die", "n", "orange", "food"],
  ["Zitrone", "die", "n", "lemon", "food"],
  ["Erdbeere", "die", "n", "strawberry", "food"],
  ["Tomate", "die", "n", "tomato", "food"],
  ["Zwiebel", "die", "n", "onion", "food"],
  ["Karotte", "die", "n", "carrot", "food"],
  ["Gurke", "die", "n", "cucumber", "food"],
  ["Traube", "die", "n", "grape", "food"],
  ["Nachtisch", "der", "n", "dessert", "food"],
  ["Gewürz", "das", "n", "spice", "food"],

  // Professions
  ["Lehrer", "der", "n", "teacher", "professions"],
  ["Arzt", "der", "n", "doctor", "professions"],
  ["Krankenschwester", "die", "n", "nurse", "professions"],
  ["Ingenieur", "der", "n", "engineer", "professions"],
  ["Polizist", "der", "n", "police officer", "professions"],
  ["Feuerwehrmann", "der", "n", "firefighter", "professions"],
  ["Koch", "der", "n", "cook", "professions"],
  ["Kellner", "der", "n", "waiter", "professions"],
  ["Verkäufer", "der", "n", "salesperson", "professions"],
  ["Fahrer", "der", "n", "driver", "professions"],
  ["Pilot", "der", "n", "pilot", "professions"],
  ["Sekretär", "der", "n", "secretary", "professions"],
  ["Anwalt", "der", "n", "lawyer", "professions"],
  ["Journalist", "der", "n", "journalist", "professions"],
  ["Künstler", "der", "n", "artist", "professions"],
  ["Musiker", "der", "n", "musician", "professions"],
  ["Bauer", "der", "n", "farmer", "professions"],
  ["Elektriker", "der", "n", "electrician", "professions"],
  ["Zahnarzt", "der", "n", "dentist", "professions"],
  ["Chef", "der", "n", "boss", "professions"],
  ["Student", "der", "n", "student", "professions"],
  ["Schüler", "der", "n", "pupil", "professions"],
  ["Kollege", "der", "n", "colleague", "professions"],
  ["Apotheker", "der", "n", "pharmacist", "professions"],
  ["Bäcker", "der", "n", "baker", "professions"],
  ["Metzger", "der", "n", "butcher", "professions"],
  ["Gärtner", "der", "n", "gardener", "professions"],
  ["Schneider", "der", "n", "tailor", "professions"],
  ["Tischler", "der", "n", "carpenter", "professions"],
  ["Maler", "der", "n", "painter", "professions"],
  ["Fotograf", "der", "n", "photographer", "professions"],

  // Countries, nationalities & languages
  ["Deutschland", "das", "n", "Germany", "countries"],
  ["Österreich", "das", "n", "Austria", "countries"],
  ["Schweiz", "die", "n", "Switzerland", "countries"],
  ["England", "das", "n", "England", "countries"],
  ["Frankreich", "das", "n", "France", "countries"],
  ["Italien", "das", "n", "Italy", "countries"],
  ["Spanien", "das", "n", "Spain", "countries"],
  ["Amerika", "das", "n", "America", "countries"],
  ["China", "das", "n", "China", "countries"],
  ["Japan", "das", "n", "Japan", "countries"],
  ["Deutsch", "das", "n", "German (language)", "countries"],
  ["Englisch", "das", "n", "English (language)", "countries"],
  ["Französisch", "das", "n", "French (language)", "countries"],
  ["Spanisch", "das", "n", "Spanish (language)", "countries"],
  ["deutsch", null, "adj", "German", "countries"],
  ["englisch", null, "adj", "English", "countries"],
  ["Land", "das", "n", "country", "countries"],
  ["Ausländer", "der", "n", "foreigner", "countries"],
  ["Heimat", "die", "n", "homeland", "countries"],
  ["Neuseeland", "das", "n", "New Zealand", "countries"],
  ["Australien", "das", "n", "Australia", "countries"],
  ["Europa", "das", "n", "Europe", "countries"],

  // Technology
  ["Tastatur", "die", "n", "keyboard", "technology"],
  ["Bildschirm", "der", "n", "screen", "technology"],
  ["Maus", "die", "n", "mouse (computer)", "technology"],
  ["Drucker", "der", "n", "printer", "technology"],
  ["Kamera", "die", "n", "camera", "technology"],
  ["Batterie", "die", "n", "battery", "technology"],
  ["Kabel", "das", "n", "cable", "technology"],
  ["Software", "die", "n", "software", "technology"],
  ["App", "die", "n", "app", "technology"],
  ["WLAN", "das", "n", "WiFi", "technology"],
  ["Ladegerät", "das", "n", "charger", "technology"],
  ["Lautsprecher", "der", "n", "speaker", "technology"],
  ["Kopfhörer", "der", "n", "headphones", "technology"],
  ["Taste", "die", "n", ["button", "key"], "technology"],

  // School
  ["Klasse", "die", "n", "class", "school"],
  ["Lehrerin", "die", "n", "teacher (f)", "school"],
  ["Hausaufgabe", "die", "n", "homework", "school"],
  ["Prüfung", "die", "n", "exam", "school"],
  ["Note", "die", "n", "grade", "school"],
  ["Kurs", "der", "n", "course", "school"],
  ["Unterricht", "der", "n", ["lessons", "class"], "school"],
  ["Lehrbuch", "das", "n", "textbook", "school"],
  ["Heft", "das", "n", "notebook", "school"],
  ["Bleistift", "der", "n", "pencil", "school"],
  ["Radiergummi", "der", "n", "eraser", "school"],
  ["Tafel", "die", "n", "blackboard", "school"],
  ["Semester", "das", "n", "semester", "school"],
  ["Zeugnis", "das", "n", "report card", "school"],

  // Health
  ["Schmerz", "der", "n", "pain", "health"],
  ["Kopfschmerzen", "die", "n", "headache", "health"],
  ["Fieber", "das", "n", "fever", "health"],
  ["Erkältung", "die", "n", "cold (illness)", "health"],
  ["Husten", "der", "n", "cough", "health"],
  ["Medikament", "das", "n", "medicine", "health"],
  ["Tablette", "die", "n", "pill", "health"],
  ["Verband", "der", "n", "bandage", "health"],
  ["Unfall", "der", "n", "accident", "health"],
  ["Notaufnahme", "die", "n", "emergency room", "health"],
  ["Krankenwagen", "der", "n", "ambulance", "health"],
  ["Termin", "der", "n", "appointment", "health"],
  ["Versicherung", "die", "n", "insurance", "health"],
  ["Allergie", "die", "n", "allergy", "health"],
  ["impfen", null, "v", ["to vaccinate", "vaccinate"], "health"],
  ["untersuchen", null, "v", ["to examine", "examine"], "health"],

  // Shopping & money
  ["Kasse", "die", "n", "checkout", "shopping"],
  ["Kassierer", "der", "n", "cashier", "shopping"],
  ["Einkaufswagen", "der", "n", "shopping cart", "shopping"],
  ["Kreditkarte", "die", "n", "credit card", "shopping"],
  ["Bargeld", "das", "n", "cash", "shopping"],
  ["Quittung", "die", "n", "receipt", "shopping"],
  ["Rabatt", "der", "n", "discount", "shopping"],
  ["Angebot", "das", "n", "offer", "shopping"],
  ["Kunde", "der", "n", "customer", "shopping"],
  ["Verkauf", "der", "n", "sale", "shopping"],
  ["kosten", null, "v", ["to cost", "cost"], "shopping"],
  ["Größe", "die", "n", "size", "shopping"],
  ["Marke", "die", "n", "brand", "shopping"],
  ["Öffnungszeiten", "die", "n", "opening hours", "shopping"],
  ["Warenhaus", "das", "n", "department store", "shopping"],

  // Nature
  ["Baum", "der", "n", "tree", "nature"],
  ["Blume", "die", "n", "flower", "nature"],
  ["Blatt", "das", "n", "leaf", "nature"],
  ["Gras", "das", "n", "grass", "nature"],
  ["Stein", "der", "n", "stone", "nature"],
  ["Sand", "der", "n", "sand", "nature"],
  ["Erde", "die", "n", ["earth", "soil"], "nature"],
  ["Himmel", "der", "n", "sky", "nature"],
  ["Wolke", "die", "n", "cloud", "nature"],
  ["Stern", "der", "n", "star", "nature"],
  ["Mond", "der", "n", "moon", "nature"],
  ["Feuer", "das", "n", "fire", "nature"],
  ["Eis", "das", "n", ["ice", "ice cream"], "nature"],
  ["Luft", "die", "n", "air", "nature"],
  ["Wüste", "die", "n", "desert", "nature"],
  ["Tal", "das", "n", "valley", "nature"],
  ["Küste", "die", "n", "coast", "nature"],
  ["Wiese", "die", "n", "meadow", "nature"],

  // More animals (wild)
  ["Löwe", "der", "n", "lion", "animals"],
  ["Tiger", "der", "n", "tiger", "animals"],
  ["Bär", "der", "n", "bear", "animals"],
  ["Affe", "der", "n", "monkey", "animals"],
  ["Elefant", "der", "n", "elephant", "animals"],
  ["Wolf", "der", "n", "wolf", "animals"],
  ["Fuchs", "der", "n", "fox", "animals"],
  ["Hase", "der", "n", "rabbit", "animals"],
  ["Schmetterling", "der", "n", "butterfly", "animals"],
  ["Biene", "die", "n", "bee", "animals"],
  ["Spinne", "die", "n", "spider", "animals"],
  ["Schlange", "die", "n", "snake", "animals"],
  ["Ente", "die", "n", "duck", "animals"],
  ["Schaf", "das", "n", "sheep", "animals"],
  ["Delfin", "der", "n", "dolphin", "animals"],
  ["Hai", "der", "n", "shark", "animals"],
  ["Wal", "der", "n", "whale", "animals"],
  ["Krokodil", "das", "n", "crocodile", "animals"],
  ["Giraffe", "die", "n", "giraffe", "animals"],
  ["Zebra", "das", "n", "zebra", "animals"],
  ["Kamel", "das", "n", "camel", "animals"],
  ["Eule", "die", "n", "owl", "animals"],
  ["Adler", "der", "n", "eagle", "animals"],
  ["Papagei", "der", "n", "parrot", "animals"],

  // Sports
  ["Basketball", "der", "n", "basketball", "hobbies"],
  ["Tennis", "das", "n", "tennis", "hobbies"],
  ["Volleyball", "der", "n", "volleyball", "hobbies"],
  ["Turnen", "das", "n", "gymnastics", "hobbies"],
  ["Yoga", "das", "n", "yoga", "hobbies"],
  ["trainieren", null, "v", ["to train", "train"], "hobbies"],
  ["Mannschaft", "die", "n", "team", "hobbies"],
  ["Trainer", "der", "n", "coach", "hobbies"],
  ["Wettbewerb", "der", "n", "competition", "hobbies"],
  ["Sieger", "der", "n", "winner", "hobbies"],
  ["Medaille", "die", "n", "medal", "hobbies"],
  ["Ski", "der", "n", "ski", "hobbies"],

  // Music
  ["Gitarre", "die", "n", "guitar", "hobbies"],
  ["Klavier", "das", "n", "piano", "hobbies"],
  ["Geige", "die", "n", "violin", "hobbies"],
  ["Trommel", "die", "n", "drum", "hobbies"],
  ["Konzert", "das", "n", "concert", "hobbies"],
  ["Lied", "das", "n", "song", "hobbies"],
  ["Band", "die", "n", "band", "hobbies"],
  ["Orchester", "das", "n", "orchestra", "hobbies"],

  // More household items
  ["Spiegel", "der", "n", "mirror", "house"],
  ["Teppich", "der", "n", "carpet", "house"],
  ["Vorhang", "der", "n", "curtain", "house"],
  ["Regal", "das", "n", "shelf", "house"],
  ["Schrank", "der", "n", "cupboard", "house"],
  ["Kissen", "das", "n", "pillow", "house"],
  ["Decke", "die", "n", ["blanket", "ceiling"], "house"],
  ["Herd", "der", "n", "stove", "house"],
  ["Ofen", "der", "n", "oven", "house"],
  ["Kühlschrank", "der", "n", "fridge", "house"],
  ["Waschmaschine", "die", "n", "washing machine", "house"],
  ["Besen", "der", "n", "broom", "house"],
  ["Eimer", "der", "n", "bucket", "house"],
  ["Handtuch", "das", "n", "towel", "house"],
  ["Seife", "die", "n", "soap", "house"],
  ["Mixer", "der", "n", "blender", "house"],
  ["Toaster", "der", "n", "toaster", "house"],
  ["Wasserkocher", "der", "n", "kettle", "house"],
  ["Sieb", "das", "n", "sieve", "house"],
  ["Reibe", "die", "n", "grater", "house"],
  ["Dosenöffner", "der", "n", "can opener", "house"],

  // Kitchen & dining
  ["Teller", "der", "n", "plate", "house"],
  ["Tasse", "die", "n", "cup", "house"],
  ["Glas", "das", "n", "glass", "house"],
  ["Messer", "das", "n", "knife", "house"],
  ["Gabel", "die", "n", "fork", "house"],
  ["Löffel", "der", "n", "spoon", "house"],
  ["Serviette", "die", "n", "napkin", "house"],
  ["Topf", "der", "n", "pot", "house"],
  ["Pfanne", "die", "n", "pan", "house"],
  ["Flasche", "die", "n", "bottle", "house"],
  ["Dose", "die", "n", "can", "house"],
  ["Schüssel", "die", "n", "bowl", "house"],
  ["Kanne", "die", "n", "pot (tea/coffee)", "house"],
  ["Tablett", "das", "n", "tray", "house"],

  // More clothing
  ["Anzug", "der", "n", "suit", "clothing"],
  ["Krawatte", "die", "n", "tie", "clothing"],
  ["Sandalen", "die", "n", "sandals", "clothing"],
  ["Stiefel", "der", "n", "boot", "clothing"],
  ["Regenmantel", "der", "n", "raincoat", "clothing"],
  ["Badeanzug", "der", "n", "swimsuit", "clothing"],
  ["Unterhemd", "das", "n", "undershirt", "clothing"],
  ["Nachthemd", "das", "n", "nightgown", "clothing"],
  ["Trainingsanzug", "der", "n", "tracksuit", "clothing"],
  ["Sonnenbrille", "die", "n", "sunglasses", "clothing"],
  ["Ohrringe", "die", "n", "earrings", "clothing"],
  ["Kette", "die", "n", ["necklace", "chain"], "clothing"],
  ["Ring", "der", "n", "ring", "clothing"],
  ["Armband", "das", "n", "bracelet", "clothing"],
  ["Rucksack", "der", "n", "backpack", "clothing"],

  // More food & drink
  ["Joghurt", "der", "n", "yogurt", "food"],
  ["Sahne", "die", "n", "cream", "food"],
  ["Öl", "das", "n", "oil", "food"],
  ["Essig", "der", "n", "vinegar", "food"],
  ["Mehl", "das", "n", "flour", "food"],
  ["Schinken", "der", "n", "ham", "food"],
  ["Wurst", "die", "n", "sausage", "food"],
  ["Speck", "der", "n", "bacon", "food"],
  ["Hähnchen", "das", "n", "chicken (meat)", "food"],
  ["Lachs", "der", "n", "salmon", "food"],
  ["Garnelen", "die", "n", "shrimp", "food"],
  ["Pilz", "der", "n", "mushroom", "food"],
  ["Bohne", "die", "n", "bean", "food"],
  ["Erbse", "die", "n", "pea", "food"],
  ["Paprika", "die", "n", "bell pepper", "food"],
  ["Spinat", "der", "n", "spinach", "food"],
  ["Kohl", "der", "n", "cabbage", "food"],
  ["Popcorn", "das", "n", "popcorn", "food"],
  ["Keks", "der", "n", "cookie", "food"],
  ["Limonade", "die", "n", "lemonade", "food"],
  ["Cola", "die", "n", "cola", "food"],

  // More adjectives
  ["reich", null, "adj", "rich", "adjectives"],
  ["arm", null, "adj", "poor", "adjectives"],
  ["breit", null, "adj", "wide", "adjectives"],
  ["schmal", null, "adj", "narrow", "adjectives"],
  ["hoch", null, "adj", "high", "adjectives"],
  ["niedrig", null, "adj", "low", "adjectives"],
  ["tief", null, "adj", "deep", "adjectives"],
  ["flach", null, "adj", "flat", "adjectives"],
  ["rund", null, "adj", "round", "adjectives"],
  ["eckig", null, "adj", "angular", "adjectives"],
  ["spitz", null, "adj", "pointy", "adjectives"],
  ["weich", null, "adj", "soft", "adjectives"],
  ["hart", null, "adj", "hard", "adjectives"],
  ["nass", null, "adj", "wet", "adjectives"],
  ["trocken", null, "adj", "dry", "adjectives"],
  ["süß", null, "adj", "sweet", "adjectives"],
  ["sauer", null, "adj", "sour", "adjectives"],
  ["bitter", null, "adj", "bitter", "adjectives"],
  ["scharf", null, "adj", "spicy", "adjectives"],
  ["salzig", null, "adj", "salty", "adjectives"],

  // More verbs
  ["kennenlernen", null, "v", ["to get to know", "meet"], "verbs"],
  ["sich vorstellen", null, "v", ["to introduce oneself", "introduce oneself"], "verbs"],
  ["gratulieren", null, "v", ["to congratulate", "congratulate"], "verbs"],
  ["feiern", null, "v", ["to celebrate", "celebrate"], "verbs"],
  ["einladen", null, "v", ["to invite", "invite"], "verbs"],
  ["absagen", null, "v", ["to cancel", "cancel"], "verbs"],
  ["zusagen", null, "v", ["to accept (an invitation)", "accept"], "verbs"],
  ["planen", null, "v", ["to plan", "plan"], "verbs"],
  ["organisieren", null, "v", ["to organize", "organize"], "verbs"],
  ["entscheiden", null, "v", ["to decide", "decide"], "verbs"],
  ["wählen", null, "v", ["to choose", "choose"], "verbs"],
  ["ändern", null, "v", ["to change", "change"], "verbs"],
  ["reparieren", null, "v", ["to repair", "repair"], "verbs"],
  ["bauen", null, "v", ["to build", "build"], "verbs"],
  ["zerstören", null, "v", ["to destroy", "destroy"], "verbs"],
  ["retten", null, "v", ["to rescue", "rescue"], "verbs"],
  ["schützen", null, "v", ["to protect", "protect"], "verbs"],
  ["kämpfen", null, "v", ["to fight", "fight"], "verbs"],
  ["gewinnen", null, "v", ["to win", "win"], "verbs"],
  ["verlieren", null, "v", ["to lose", "lose"], "verbs"],
  ["träumen", null, "v", ["to dream", "dream"], "verbs"],
  ["hoffen", null, "v", ["to hope", "hope"], "verbs"],
  ["glauben", null, "v", ["to believe", "believe"], "verbs"],
  ["meinen", null, "v", ["to mean", "to think (opinion)"], "verbs"],
  ["vermuten", null, "v", ["to suspect", "suspect"], "verbs"],
  ["sich erinnern", null, "v", ["to remember", "remember"], "verbs"],
  ["sich beschweren", null, "v", ["to complain", "complain"], "verbs"],
  ["sich entschuldigen", null, "v", ["to apologize", "apologize"], "verbs"],
  ["aufpassen", null, "v", ["to pay attention", "pay attention"], "verbs"],
  ["zuhören", null, "v", ["to listen", "listen"], "verbs"],
  ["mitmachen", null, "v", ["to join in", "join in"], "verbs"],
  ["teilnehmen", null, "v", ["to participate", "participate"], "verbs"],
  ["sich konzentrieren", null, "v", ["to concentrate", "concentrate"], "verbs"],
  ["sich entspannen", null, "v", ["to relax", "relax"], "verbs"],
  ["sich ausruhen", null, "v", ["to rest", "rest"], "verbs"],
  ["sich beeilen", null, "v", ["to hurry", "hurry"], "verbs"],
  ["nachdenken", null, "v", ["to think over", "think over"], "verbs"],
  ["sich erholen", null, "v", ["to recover", "recover"], "verbs"],
  ["sich verlieben", null, "v", ["to fall in love", "fall in love"], "verbs"],
  ["heiraten", null, "v", ["to marry", "marry"], "verbs"],
  ["sich streiten", null, "v", ["to argue", "argue"], "verbs"],
  ["sich versöhnen", null, "v", ["to make up", "make up"], "verbs"],
  ["loben", null, "v", ["to praise", "praise"], "verbs"],
  ["kritisieren", null, "v", ["to criticize", "criticize"], "verbs"],
  ["beschreiben", null, "v", ["to describe", "describe"], "verbs"],
  ["vergleichen", null, "v", ["to compare", "compare"], "verbs"],
  ["empfehlen", null, "v", ["to recommend", "recommend"], "verbs"],
  ["vorschlagen", null, "v", ["to suggest", "suggest"], "verbs"],
  ["ablehnen", null, "v", ["to reject", "reject"], "verbs"],
  ["akzeptieren", null, "v", ["to accept", "accept"], "verbs"],
  ["überzeugen", null, "v", ["to convince", "convince"], "verbs"],
  ["beeindrucken", null, "v", ["to impress", "impress"], "verbs"],
  ["überraschen", null, "v", ["to surprise", "surprise"], "verbs"],
  ["enttäuschen", null, "v", ["to disappoint", "disappoint"], "verbs"],
  ["ärgern", null, "v", ["to annoy", "annoy"], "verbs"],
  ["beruhigen", null, "v", ["to calm", "calm"], "verbs"],
  ["trösten", null, "v", ["to comfort", "comfort"], "verbs"],
  ["sich freuen", null, "v", ["to be happy", "be glad"], "verbs"],
  ["sich vorbereiten", null, "v", ["to prepare", "prepare"], "verbs"],

  // More time expressions
  ["Kalender", "der", "n", "calendar", "time"],
  ["Datum", "das", "n", "date", "time"],
  ["Jahrhundert", "das", "n", "century", "time"],
  ["Jahrzehnt", "das", "n", "decade", "time"],
  ["Vergangenheit", "die", "n", "past", "time"],
  ["Gegenwart", "die", "n", "present", "time"],
  ["Zukunft", "die", "n", "future", "time"],
  ["Moment", "der", "n", "moment", "time"],
  ["Uhrzeit", "die", "n", "time (clock)", "time"],

  // Emotions & feelings
  ["Angst", "die", "n", "fear", "misc"],
  ["Freude", "die", "n", "joy", "misc"],
  ["Wut", "die", "n", "anger", "misc"],
  ["Liebe", "die", "n", "love", "misc"],
  ["Hoffnung", "die", "n", "hope", "misc"],
  ["Eifersucht", "die", "n", "jealousy", "misc"],
  ["Stolz", "der", "n", "pride", "misc"],
  ["Scham", "die", "n", "shame", "misc"],
  ["Überraschung", "die", "n", "surprise", "misc"],
  ["Langeweile", "die", "n", "boredom", "misc"],
  ["Aufregung", "die", "n", "excitement", "misc"],
  ["Ruhe", "die", "n", "calm", "misc"],
  ["Zufriedenheit", "die", "n", "satisfaction", "misc"],
  ["Enttäuschung", "die", "n", "disappointment", "misc"],

  // More family
  ["Cousin", "der", "n", "cousin (m)", "family"],
  ["Cousine", "die", "n", "cousin (f)", "family"],
  ["Nichte", "die", "n", "niece", "family"],
  ["Neffe", "der", "n", "nephew", "family"],
  ["Schwiegermutter", "die", "n", "mother-in-law", "family"],
  ["Schwiegervater", "der", "n", "father-in-law", "family"],
  ["Enkel", "der", "n", "grandson", "family"],
  ["Enkelin", "die", "n", "granddaughter", "family"],
  ["Verwandte", "der", "n", "relative", "family"],
  ["Zwilling", "der", "n", "twin", "family"],

  // Measurements
  ["Kilogramm", "das", "n", "kilogram", "numbers"],
  ["Gramm", "das", "n", "gram", "numbers"],
  ["Liter", "der", "n", "liter", "numbers"],
  ["Meter", "der", "n", "meter", "numbers"],
  ["Zentimeter", "der", "n", "centimeter", "numbers"],
  ["Kilometer", "der", "n", "kilometer", "numbers"],
  ["Gewicht", "das", "n", "weight", "numbers"],
  ["Länge", "die", "n", "length", "numbers"],
  ["Breite", "die", "n", "width", "numbers"],
  ["Höhe", "die", "n", "height", "numbers"],
  ["Prozent", "das", "n", "percent", "numbers"],

  // More transport
  ["Koffer", "der", "n", "suitcase", "transport"],
  ["Gepäck", "das", "n", "luggage", "transport"],
  ["Reisepass", "der", "n", "passport", "transport"],
  ["Visum", "das", "n", "visa", "transport"],
  ["Zoll", "der", "n", "customs", "transport"],
  ["Ausweis", "der", "n", "ID card", "transport"],
  ["Führerschein", "der", "n", "driver's license", "transport"],
  ["Parkplatz", "der", "n", "parking lot", "transport"],

  // More places
  ["Rathaus", "das", "n", "town hall", "places"],
  ["Gericht", "das", "n", "court", "places"],
  ["Gefängnis", "das", "n", "prison", "places"],
  ["Fabrik", "die", "n", "factory", "places"],
  ["Firma", "die", "n", "company", "places"],
  ["Botschaft", "die", "n", "embassy", "places"],
  ["Konsulat", "das", "n", "consulate", "places"],
  ["Grenze", "die", "n", "border", "places"],
  ["Autobahn", "die", "n", "highway", "places"],
  ["Kreuzung", "die", "n", "intersection", "places"],

  // Common phrases & expressions
  ["Herzlichen Glückwunsch", null, "phrase", "congratulations", "greetings"],
  ["Alles Gute", null, "phrase", "all the best", "greetings"],
  ["Viel Glück", null, "phrase", "good luck", "greetings"],
  ["Gute Besserung", null, "phrase", "get well soon", "greetings"],
  ["Guten Appetit", null, "phrase", "enjoy your meal", "greetings"],
  ["Prost", null, "phrase", "cheers", "greetings"],
  ["Kein Problem", null, "phrase", "no problem", "greetings"],
  ["Macht nichts", null, "phrase", "never mind", "greetings"],
  ["Es tut mir leid", null, "phrase", "I'm sorry", "greetings"],
  ["Gute Reise", null, "phrase", "safe travels", "greetings"],

  // More misc nouns
  ["Ziel", "das", "n", "goal", "misc"],
  ["Erfolg", "der", "n", "success", "misc"],
  ["Fehler", "der", "n", "mistake", "misc"],
  ["Chance", "die", "n", "chance", "misc"],
  ["Möglichkeit", "die", "n", "possibility", "misc"],
  ["Wahrheit", "die", "n", "truth", "misc"],
  ["Lüge", "die", "n", "lie", "misc"],
  ["Geheimnis", "das", "n", "secret", "misc"],
  ["Überzeugung", "die", "n", "conviction", "misc"],
  ["Meinung", "die", "n", "opinion", "misc"],
  ["Entscheidung", "die", "n", "decision", "misc"],
  ["Ergebnis", "das", "n", "result", "misc"],
  ["Unterschied", "der", "n", "difference", "misc"],
  ["Vorteil", "der", "n", "advantage", "misc"],
  ["Nachteil", "der", "n", "disadvantage", "misc"],
  ["Bedeutung", "die", "n", "meaning", "misc"],
  ["Wert", "der", "n", "value", "misc"],
  ["Qualität", "die", "n", "quality", "misc"],
  ["Menge", "die", "n", "amount", "misc"],
  ["Anzahl", "die", "n", "number (of)", "misc"],
  ["Reihenfolge", "die", "n", "order (sequence)", "misc"],
  ["Ordnung", "die", "n", "order (tidiness)", "misc"],
  ["System", "das", "n", "system", "misc"],
  ["Methode", "die", "n", "method", "misc"],
  ["Prozess", "der", "n", "process", "misc"],
  ["Wirkung", "die", "n", "effect", "misc"],
  ["Einfluss", "der", "n", "influence", "misc"],
  ["Verantwortung", "die", "n", "responsibility", "misc"],
  ["Erfahrung", "die", "n", "experience", "misc"],

  // More adverbs
  ["draußen", null, "adv", "outside", "adverbs"],
  ["drinnen", null, "adv", "inside", "adverbs"],
  ["überall", null, "adv", "everywhere", "adverbs"],
  ["nirgendwo", null, "adv", "nowhere", "adverbs"],
  ["irgendwo", null, "adv", "somewhere", "adverbs"],
  ["irgendwann", null, "adv", "sometime", "adverbs"],
  ["plötzlich", null, "adv", "suddenly", "adverbs"],
  ["allmählich", null, "adv", "gradually", "adverbs"],
  ["ständig", null, "adv", "constantly", "adverbs"],
  ["regelmäßig", null, "adv", "regularly", "adverbs"],
  ["gelegentlich", null, "adv", "occasionally", "adverbs"],
  ["insgesamt", null, "adv", "in total", "adverbs"],

  // More weather
  ["Blitz", "der", "n", "lightning", "weather"],
  ["Donner", "der", "n", "thunder", "weather"],
  ["Nebel", "der", "n", "fog", "weather"],
  ["Frost", "der", "n", "frost", "weather"],
  ["Hitze", "die", "n", "heat", "weather"],
  ["Sturm", "der", "n", "storm", "weather"],
  ["Gewitter", "das", "n", "thunderstorm", "weather"],

  // More body/health
  ["Muskel", "der", "n", "muscle", "body"],
  ["Knochen", "der", "n", "bone", "body"],
  ["Gehirn", "das", "n", "brain", "body"],
  ["Lunge", "die", "n", "lung", "body"],
  ["Leber", "die", "n", "liver", "body"],
  ["Niere", "die", "n", "kidney", "body"],
  ["Blut", "das", "n", "blood", "body"],
  ["Puls", "der", "n", "pulse", "body"],

  // More question/grammar words
  ["welcher", null, "pron", "which (one)", "questions"],
  ["welches", null, "pron", "which (one, neuter)", "questions"],
  ["wessen", null, "pron", "whose", "questions"],
  ["wodurch", null, "adv", "through which", "questions"],
  ["wobei", null, "adv", "whereby", "questions"],
  ["weshalb", null, "adv", "for what reason", "questions"],
];

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const idCounts = {};
const WORDS = RAW.map((r) => {
  let id = `${r[2]}-${slugify(r[0])}`; // stable id: part-of-speech + slugified word, not array position
  idCounts[id] = (idCounts[id] || 0) + 1;
  if (idCounts[id] > 1) id = `${id}-${idCounts[id]}`; // disambiguate genuine homographs
  return {
    id,
    de: r[0],
    article: r[1],
    pos: r[2],
    en: Array.isArray(r[3]) ? r[3] : [r[3]],
    cat: r[4],
  };
});

const WORD_BY_ID = Object.fromEntries(WORDS.map((w) => [w.id, w]));

const CAT_LABELS = {
  greetings: "Greetings",
  pronouns: "Pronouns",
  questions: "Question words",
  numbers: "Numbers",
  colors: "Colors",
  family: "Family",
  food: "Food & drink",
  time: "Time & calendar",
  weather: "Weather",
  body: "Body",
  clothing: "Clothing",
  house: "House",
  places: "Places",
  transport: "Transport",
  verbs: "Verbs",
  adjectives: "Adjectives",
  grammar: "Prepositions & conjunctions",
  misc: "Everyday things",
  directions: "Directions",
  adverbs: "Adverbs & quantifiers",
  animals: "Animals",
  hobbies: "Hobbies & leisure",
  professions: "Professions",
  countries: "Countries & languages",
  technology: "Technology",
  school: "School",
  health: "Health",
  shopping: "Shopping & money",
  nature: "Nature",
};
