/* ----------------------------------------------------------------------
   A1 GERMAN VOCABULARY DATA
   [de, article|null, pos, en(string|array), category]
------------------------------------------------------------------------*/
const RAW = [
  // Greetings & phrases
  ["Hallo", null, "phrase", "hello", "greetings"],
  ["Guten Morgen", null, "phrase", "good morning", "greetings"],
  ["Guten Tag", null, "phrase", "good day", "greetings"],
  ["Guten Abend", null, "phrase", "good evening", "greetings"],
  ["Gute Nacht", null, "phrase", "good night", "greetings"],
  ["Auf Wiedersehen", null, "phrase", "goodbye", "greetings"],
  ["Tschüss", null, "phrase", "bye", "greetings"],
  ["Bis bald", null, "phrase", "see you soon", "greetings"],
  ["Bitte", null, "phrase", ["please", "you're welcome"], "greetings"],
  ["Danke", null, "phrase", "thank you", "greetings"],
  ["Entschuldigung", null, "phrase", ["excuse me", "sorry"], "greetings"],
  ["Ja", null, "phrase", "yes", "greetings"],
  ["Nein", null, "phrase", "no", "greetings"],
  ["Vielleicht", null, "adv", "maybe", "greetings"],
  ["Wie geht es dir", null, "phrase", "how are you", "greetings"],
  ["Mir geht es gut", null, "phrase", "I'm fine", "greetings"],
  ["Willkommen", null, "phrase", "welcome", "greetings"],

  // Pronouns
  ["ich", null, "pron", "I", "pronouns"],
  ["du", null, "pron", "you", "pronouns"],
  ["er", null, "pron", "he", "pronouns"],
  ["sie", null, "pron", "she", "pronouns"],
  ["es", null, "pron", "it", "pronouns"],
  ["wir", null, "pron", "we", "pronouns"],
  ["ihr", null, "pron", "you (plural)", "pronouns"],
  ["mein", null, "pron", "my", "pronouns"],
  ["dein", null, "pron", "your", "pronouns"],
  ["sein", null, "pron", "his", "pronouns"],
  ["unser", null, "pron", "our", "pronouns"],

  // Question words
  ["wer", null, "pron", "who", "questions"],
  ["was", null, "pron", "what", "questions"],
  ["wo", null, "adv", "where", "questions"],
  ["wann", null, "adv", "when", "questions"],
  ["warum", null, "adv", "why", "questions"],
  ["wie", null, "adv", "how", "questions"],
  ["welche", null, "pron", "which", "questions"],

  // Numbers
  ["null", null, "num", "zero", "numbers"],
  ["eins", null, "num", "one", "numbers"],
  ["zwei", null, "num", "two", "numbers"],
  ["drei", null, "num", "three", "numbers"],
  ["vier", null, "num", "four", "numbers"],
  ["fünf", null, "num", "five", "numbers"],
  ["sechs", null, "num", "six", "numbers"],
  ["sieben", null, "num", "seven", "numbers"],
  ["acht", null, "num", "eight", "numbers"],
  ["neun", null, "num", "nine", "numbers"],
  ["zehn", null, "num", "ten", "numbers"],
  ["elf", null, "num", "eleven", "numbers"],
  ["zwölf", null, "num", "twelve", "numbers"],
  ["dreizehn", null, "num", "thirteen", "numbers"],
  ["vierzehn", null, "num", "fourteen", "numbers"],
  ["fünfzehn", null, "num", "fifteen", "numbers"],
  ["zwanzig", null, "num", "twenty", "numbers"],
  ["dreißig", null, "num", "thirty", "numbers"],
  ["vierzig", null, "num", "forty", "numbers"],
  ["fünfzig", null, "num", "fifty", "numbers"],
  ["hundert", null, "num", "hundred", "numbers"],
  ["tausend", null, "num", "thousand", "numbers"],

  // Colors
  ["rot", null, "adj", "red", "colors"],
  ["blau", null, "adj", "blue", "colors"],
  ["gelb", null, "adj", "yellow", "colors"],
  ["grün", null, "adj", "green", "colors"],
  ["schwarz", null, "adj", "black", "colors"],
  ["weiß", null, "adj", "white", "colors"],
  ["braun", null, "adj", "brown", "colors"],
  ["orange", null, "adj", "orange", "colors"],
  ["rosa", null, "adj", "pink", "colors"],
  ["grau", null, "adj", "grey", "colors"],
  ["lila", null, "adj", "purple", "colors"],

  // Family
  ["Familie", "die", "n", "family", "family"],
  ["Mutter", "die", "n", "mother", "family"],
  ["Vater", "der", "n", "father", "family"],
  ["Schwester", "die", "n", "sister", "family"],
  ["Bruder", "der", "n", "brother", "family"],
  ["Tochter", "die", "n", "daughter", "family"],
  ["Sohn", "der", "n", "son", "family"],
  ["Großmutter", "die", "n", "grandmother", "family"],
  ["Großvater", "der", "n", "grandfather", "family"],
  ["Frau", "die", "n", ["woman", "wife"], "family"],
  ["Mann", "der", "n", ["man", "husband"], "family"],
  ["Kind", "das", "n", "child", "family"],
  ["Eltern", "die", "n", "parents", "family"],
  ["Tante", "die", "n", "aunt", "family"],
  ["Onkel", "der", "n", "uncle", "family"],
  ["Freund", "der", "n", ["friend", "boyfriend"], "family"],
  ["Freundin", "die", "n", ["friend", "girlfriend"], "family"],

  // Food & drink
  ["Brot", "das", "n", "bread", "food"],
  ["Käse", "der", "n", "cheese", "food"],
  ["Milch", "die", "n", "milk", "food"],
  ["Wasser", "das", "n", "water", "food"],
  ["Kaffee", "der", "n", "coffee", "food"],
  ["Tee", "der", "n", "tea", "food"],
  ["Apfel", "der", "n", "apple", "food"],
  ["Banane", "die", "n", "banana", "food"],
  ["Ei", "das", "n", "egg", "food"],
  ["Zucker", "der", "n", "sugar", "food"],
  ["Salz", "das", "n", "salt", "food"],
  ["Suppe", "die", "n", "soup", "food"],
  ["Fleisch", "das", "n", "meat", "food"],
  ["Fisch", "der", "n", "fish", "food"],
  ["Gemüse", "das", "n", "vegetables", "food"],
  ["Reis", "der", "n", "rice", "food"],
  ["Kartoffel", "die", "n", "potato", "food"],
  ["Saft", "der", "n", "juice", "food"],
  ["Wein", "der", "n", "wine", "food"],
  ["Bier", "das", "n", "beer", "food"],
  ["Frühstück", "das", "n", "breakfast", "food"],
  ["Mittagessen", "das", "n", "lunch", "food"],
  ["Abendessen", "das", "n", "dinner", "food"],
  ["Kuchen", "der", "n", "cake", "food"],
  ["Schokolade", "die", "n", "chocolate", "food"],

  // Time & calendar
  ["Zeit", "die", "n", "time", "time"],
  ["Stunde", "die", "n", "hour", "time"],
  ["Minute", "die", "n", "minute", "time"],
  ["Tag", "der", "n", "day", "time"],
  ["Woche", "die", "n", "week", "time"],
  ["Monat", "der", "n", "month", "time"],
  ["Jahr", "das", "n", "year", "time"],
  ["heute", null, "adv", "today", "time"],
  ["morgen", null, "adv", "tomorrow", "time"],
  ["gestern", null, "adv", "yesterday", "time"],
  ["Montag", "der", "n", "Monday", "time"],
  ["Dienstag", "der", "n", "Tuesday", "time"],
  ["Mittwoch", "der", "n", "Wednesday", "time"],
  ["Donnerstag", "der", "n", "Thursday", "time"],
  ["Freitag", "der", "n", "Friday", "time"],
  ["Samstag", "der", "n", "Saturday", "time"],
  ["Sonntag", "der", "n", "Sunday", "time"],
  ["Januar", "der", "n", "January", "time"],
  ["Februar", "der", "n", "February", "time"],
  ["März", "der", "n", "March", "time"],
  ["April", "der", "n", "April", "time"],
  ["Mai", "der", "n", "May", "time"],
  ["Juni", "der", "n", "June", "time"],
  ["Juli", "der", "n", "July", "time"],
  ["August", "der", "n", "August", "time"],
  ["September", "der", "n", "September", "time"],
  ["Oktober", "der", "n", "October", "time"],
  ["November", "der", "n", "November", "time"],
  ["Dezember", "der", "n", "December", "time"],
  ["Frühling", "der", "n", "spring", "time"],
  ["Sommer", "der", "n", "summer", "time"],
  ["Herbst", "der", "n", "autumn", "time"],
  ["Winter", "der", "n", "winter", "time"],

  // Weather
  ["Wetter", "das", "n", "weather", "weather"],
  ["Sonne", "die", "n", "sun", "weather"],
  ["Regen", "der", "n", "rain", "weather"],
  ["Schnee", "der", "n", "snow", "weather"],
  ["Wind", "der", "n", "wind", "weather"],
  ["warm", null, "adj", "warm", "weather"],
  ["kalt", null, "adj", "cold", "weather"],
  ["heiß", null, "adj", "hot", "weather"],
  ["kühl", null, "adj", "cool", "weather"],

  // Body
  ["Kopf", "der", "n", "head", "body"],
  ["Auge", "das", "n", "eye", "body"],
  ["Nase", "die", "n", "nose", "body"],
  ["Mund", "der", "n", "mouth", "body"],
  ["Ohr", "das", "n", "ear", "body"],
  ["Hand", "die", "n", "hand", "body"],
  ["Fuß", "der", "n", "foot", "body"],
  ["Arm", "der", "n", "arm", "body"],
  ["Bein", "das", "n", "leg", "body"],
  ["Bauch", "der", "n", "stomach", "body"],
  ["Haar", "das", "n", "hair", "body"],
  ["Rücken", "der", "n", "back", "body"],

  // Clothing
  ["Kleidung", "die", "n", "clothing", "clothing"],
  ["Hemd", "das", "n", "shirt", "clothing"],
  ["Hose", "die", "n", "trousers", "clothing"],
  ["Rock", "der", "n", "skirt", "clothing"],
  ["Kleid", "das", "n", "dress", "clothing"],
  ["Jacke", "die", "n", "jacket", "clothing"],
  ["Schuhe", "die", "n", "shoes", "clothing"],
  ["Hut", "der", "n", "hat", "clothing"],
  ["Mütze", "die", "n", "cap", "clothing"],

  // House
  ["Haus", "das", "n", "house", "house"],
  ["Wohnung", "die", "n", "apartment", "house"],
  ["Zimmer", "das", "n", "room", "house"],
  ["Küche", "die", "n", "kitchen", "house"],
  ["Bad", "das", "n", "bathroom", "house"],
  ["Schlafzimmer", "das", "n", "bedroom", "house"],
  ["Wohnzimmer", "das", "n", "living room", "house"],
  ["Tisch", "der", "n", "table", "house"],
  ["Stuhl", "der", "n", "chair", "house"],
  ["Bett", "das", "n", "bed", "house"],
  ["Tür", "die", "n", "door", "house"],
  ["Fenster", "das", "n", "window", "house"],
  ["Wand", "die", "n", "wall", "house"],
  ["Boden", "der", "n", "floor", "house"],
  ["Lampe", "die", "n", "lamp", "house"],

  // Places
  ["Stadt", "die", "n", "city", "places"],
  ["Dorf", "das", "n", "village", "places"],
  ["Straße", "die", "n", "street", "places"],
  ["Park", "der", "n", "park", "places"],
  ["Schule", "die", "n", "school", "places"],
  ["Universität", "die", "n", "university", "places"],
  ["Krankenhaus", "das", "n", "hospital", "places"],
  ["Bahnhof", "der", "n", "train station", "places"],
  ["Flughafen", "der", "n", "airport", "places"],
  ["Geschäft", "das", "n", "shop", "places"],
  ["Supermarkt", "der", "n", "supermarket", "places"],
  ["Restaurant", "das", "n", "restaurant", "places"],
  ["Hotel", "das", "n", "hotel", "places"],
  ["Kirche", "die", "n", "church", "places"],
  ["Bibliothek", "die", "n", "library", "places"],
  ["Büro", "das", "n", "office", "places"],
  ["Markt", "der", "n", "market", "places"],

  // Transport
  ["Auto", "das", "n", "car", "transport"],
  ["Bus", "der", "n", "bus", "transport"],
  ["Zug", "der", "n", "train", "transport"],
  ["Fahrrad", "das", "n", "bicycle", "transport"],
  ["Flugzeug", "das", "n", "airplane", "transport"],
  ["Schiff", "das", "n", "ship", "transport"],
  ["U-Bahn", "die", "n", "subway", "transport"],
  ["Taxi", "das", "n", "taxi", "transport"],

  // Verbs
  ["sein", null, "v", ["to be", "be"], "verbs"],
  ["haben", null, "v", ["to have", "have"], "verbs"],
  ["werden", null, "v", ["to become", "become"], "verbs"],
  ["gehen", null, "v", ["to go", "go"], "verbs"],
  ["kommen", null, "v", ["to come", "come"], "verbs"],
  ["machen", null, "v", ["to make", "to do", "do"], "verbs"],
  ["sagen", null, "v", ["to say", "say"], "verbs"],
  ["sehen", null, "v", ["to see", "see"], "verbs"],
  ["wissen", null, "v", ["to know", "know"], "verbs"],
  ["geben", null, "v", ["to give", "give"], "verbs"],
  ["nehmen", null, "v", ["to take", "take"], "verbs"],
  ["finden", null, "v", ["to find", "find"], "verbs"],
  ["denken", null, "v", ["to think", "think"], "verbs"],
  ["bleiben", null, "v", ["to stay", "stay"], "verbs"],
  ["liegen", null, "v", ["to lie", "lie down"], "verbs"],
  ["sitzen", null, "v", ["to sit", "sit"], "verbs"],
  ["stehen", null, "v", ["to stand", "stand"], "verbs"],
  ["arbeiten", null, "v", ["to work", "work"], "verbs"],
  ["spielen", null, "v", ["to play", "play"], "verbs"],
  ["lernen", null, "v", ["to learn", "learn"], "verbs"],
  ["essen", null, "v", ["to eat", "eat"], "verbs"],
  ["trinken", null, "v", ["to drink", "drink"], "verbs"],
  ["schlafen", null, "v", ["to sleep", "sleep"], "verbs"],
  ["leben", null, "v", ["to live", "live"], "verbs"],
  ["lieben", null, "v", ["to love", "love"], "verbs"],
  ["mögen", null, "v", ["to like", "like"], "verbs"],
  ["brauchen", null, "v", ["to need", "need"], "verbs"],
  ["kaufen", null, "v", ["to buy", "buy"], "verbs"],
  ["verkaufen", null, "v", ["to sell", "sell"], "verbs"],
  ["kochen", null, "v", ["to cook", "cook"], "verbs"],
  ["lesen", null, "v", ["to read", "read"], "verbs"],
  ["schreiben", null, "v", ["to write", "write"], "verbs"],
  ["sprechen", null, "v", ["to speak", "speak"], "verbs"],
  ["hören", null, "v", ["to hear", "to listen", "listen"], "verbs"],
  ["fragen", null, "v", ["to ask", "ask"], "verbs"],
  ["antworten", null, "v", ["to answer", "answer"], "verbs"],
  ["helfen", null, "v", ["to help", "help"], "verbs"],
  ["verstehen", null, "v", ["to understand", "understand"], "verbs"],
  ["fahren", null, "v", ["to drive", "to go (by vehicle)", "drive"], "verbs"],
  ["fliegen", null, "v", ["to fly", "fly"], "verbs"],
  ["laufen", null, "v", ["to run", "to walk", "run"], "verbs"],
  ["tanzen", null, "v", ["to dance", "dance"], "verbs"],
  ["singen", null, "v", ["to sing", "sing"], "verbs"],
  ["kennen", null, "v", ["to know", "to be familiar with", "know"], "verbs"],
  ["wohnen", null, "v", ["to live", "to reside", "reside"], "verbs"],
  ["heißen", null, "v", ["to be called", "be named"], "verbs"],
  ["öffnen", null, "v", ["to open", "open"], "verbs"],
  ["schließen", null, "v", ["to close", "close"], "verbs"],
  ["warten", null, "v", ["to wait", "wait"], "verbs"],

  // Adjectives
  ["groß", null, "adj", ["big", "tall"], "adjectives"],
  ["klein", null, "adj", "small", "adjectives"],
  ["gut", null, "adj", "good", "adjectives"],
  ["schlecht", null, "adj", "bad", "adjectives"],
  ["neu", null, "adj", "new", "adjectives"],
  ["alt", null, "adj", "old", "adjectives"],
  ["jung", null, "adj", "young", "adjectives"],
  ["schön", null, "adj", ["beautiful", "nice"], "adjectives"],
  ["hässlich", null, "adj", "ugly", "adjectives"],
  ["schnell", null, "adj", "fast", "adjectives"],
  ["langsam", null, "adj", "slow", "adjectives"],
  ["leicht", null, "adj", ["easy", "light"], "adjectives"],
  ["schwer", null, "adj", ["difficult", "heavy"], "adjectives"],
  ["teuer", null, "adj", "expensive", "adjectives"],
  ["billig", null, "adj", "cheap", "adjectives"],
  ["glücklich", null, "adj", "happy", "adjectives"],
  ["traurig", null, "adj", "sad", "adjectives"],
  ["müde", null, "adj", "tired", "adjectives"],
  ["hungrig", null, "adj", "hungry", "adjectives"],
  ["durstig", null, "adj", "thirsty", "adjectives"],
  ["sauber", null, "adj", "clean", "adjectives"],
  ["schmutzig", null, "adj", "dirty", "adjectives"],
  ["laut", null, "adj", "loud", "adjectives"],
  ["leise", null, "adj", "quiet", "adjectives"],
  ["wichtig", null, "adj", "important", "adjectives"],
  ["richtig", null, "adj", "correct", "adjectives"],
  ["falsch", null, "adj", "wrong", "adjectives"],
  ["voll", null, "adj", "full", "adjectives"],
  ["leer", null, "adj", "empty", "adjectives"],
  ["offen", null, "adj", "open", "adjectives"],
  ["geschlossen", null, "adj", "closed", "adjectives"],

  // Prepositions & conjunctions
  ["in", null, "prep", "in", "grammar"],
  ["auf", null, "prep", "on", "grammar"],
  ["unter", null, "prep", "under", "grammar"],
  ["über", null, "prep", "over", "grammar"],
  ["neben", null, "prep", "next to", "grammar"],
  ["vor", null, "prep", ["in front of", "before"], "grammar"],
  ["hinter", null, "prep", "behind", "grammar"],
  ["zwischen", null, "prep", "between", "grammar"],
  ["mit", null, "prep", "with", "grammar"],
  ["ohne", null, "prep", "without", "grammar"],
  ["für", null, "prep", "for", "grammar"],
  ["gegen", null, "prep", "against", "grammar"],
  ["und", null, "conj", "and", "grammar"],
  ["oder", null, "conj", "or", "grammar"],
  ["aber", null, "conj", "but", "grammar"],
  ["weil", null, "conj", "because", "grammar"],
  ["dass", null, "conj", "that", "grammar"],
  ["wenn", null, "conj", "if", "grammar"],

  // Misc nouns
  ["Name", "der", "n", "name", "misc"],
  ["Adresse", "die", "n", "address", "misc"],
  ["Telefonnummer", "die", "n", "phone number", "misc"],
  ["Arbeit", "die", "n", "work", "misc"],
  ["Beruf", "der", "n", "job", "misc"],
  ["Geld", "das", "n", "money", "misc"],
  ["Zeitung", "die", "n", "newspaper", "misc"],
  ["Buch", "das", "n", "book", "misc"],
  ["Stift", "der", "n", "pen", "misc"],
  ["Papier", "das", "n", "paper", "misc"],
  ["Tasche", "die", "n", "bag", "misc"],
  ["Schlüssel", "der", "n", "key", "misc"],
  ["Handy", "das", "n", "mobile phone", "misc"],
  ["Computer", "der", "n", "computer", "misc"],
  ["Foto", "das", "n", "photo", "misc"],
  ["Musik", "die", "n", "music", "misc"],
  ["Film", "der", "n", "film", "misc"],
  ["Spiel", "das", "n", "game", "misc"],
  ["Sprache", "die", "n", "language", "misc"],
  ["Welt", "die", "n", "world", "misc"],

  // Numbers & ordinals (extra)
  ["sechzehn", null, "num", "sixteen", "numbers"],
  ["siebzehn", null, "num", "seventeen", "numbers"],
  ["achtzehn", null, "num", "eighteen", "numbers"],
  ["neunzehn", null, "num", "nineteen", "numbers"],
  ["sechzig", null, "num", "sixty", "numbers"],
  ["siebzig", null, "num", "seventy", "numbers"],
  ["achtzig", null, "num", "eighty", "numbers"],
  ["neunzig", null, "num", "ninety", "numbers"],
  ["erste", null, "num", "first", "numbers"],
  ["zweite", null, "num", "second", "numbers"],
  ["dritte", null, "num", "third", "numbers"],
  ["letzte", null, "num", "last", "numbers"],
  ["Million", "die", "n", "million", "numbers"],
  ["Nummer", "die", "n", "number", "numbers"],

  // Time (extra)
  ["Uhr", "die", "n", ["o'clock", "clock"], "time"],
  ["Mittag", "der", "n", "midday", "time"],
  ["Mitternacht", "die", "n", "midnight", "time"],
  ["Vormittag", "der", "n", "late morning", "time"],
  ["Nachmittag", "der", "n", "afternoon", "time"],
  ["Wochenende", "das", "n", "weekend", "time"],
  ["Feiertag", "der", "n", "public holiday", "time"],

  // Directions
  ["links", null, "adv", "left", "directions"],
  ["rechts", null, "adv", "right", "directions"],
  ["geradeaus", null, "adv", "straight ahead", "directions"],
  ["oben", null, "adv", ["above", "upstairs"], "directions"],
  ["unten", null, "adv", ["below", "downstairs"], "directions"],
  ["hier", null, "adv", "here", "directions"],
  ["dort", null, "adv", "there", "directions"],

  // Adverbs & quantifiers
  ["auch", null, "adv", "also", "adverbs"],
  ["sehr", null, "adv", "very", "adverbs"],
  ["immer", null, "adv", "always", "adverbs"],
  ["nie", null, "adv", "never", "adverbs"],
  ["schon", null, "adv", "already", "adverbs"],
  ["noch", null, "adv", "still", "adverbs"],
  ["jetzt", null, "adv", "now", "adverbs"],
  ["später", null, "adv", "later", "adverbs"],
  ["früher", null, "adv", "earlier", "adverbs"],
  ["zusammen", null, "adv", "together", "adverbs"],
  ["allein", null, "adv", "alone", "adverbs"],
  ["wieder", null, "adv", "again", "adverbs"],
  ["nur", null, "adv", "only", "adverbs"],
  ["fast", null, "adv", "almost", "adverbs"],
  ["genau", null, "adv", "exactly", "adverbs"],
  ["wirklich", null, "adv", "really", "adverbs"],
  ["natürlich", null, "adv", "naturally", "adverbs"],
  ["leider", null, "adv", "unfortunately", "adverbs"],
  ["gern", null, "adv", "gladly", "adverbs"],
  ["oft", null, "adv", "often", "adverbs"],
  ["manchmal", null, "adv", "sometimes", "adverbs"],
  ["etwas", null, "pron", "something", "adverbs"],
  ["nichts", null, "pron", "nothing", "adverbs"],
  ["alles", null, "pron", "everything", "adverbs"],

  // Modal verbs
  ["können", null, "v", ["can", "to be able to"], "verbs"],
  ["müssen", null, "v", ["must", "to have to"], "verbs"],
  ["dürfen", null, "v", ["may", "to be allowed to"], "verbs"],
  ["sollen", null, "v", ["should", "to be supposed to"], "verbs"],
  ["wollen", null, "v", ["to want", "want"], "verbs"],
  ["möchten", null, "v", ["would like", "want"], "verbs"],

  // More verbs
  ["anfangen", null, "v", ["to begin", "begin"], "verbs"],
  ["aufhören", null, "v", ["to stop", "stop"], "verbs"],
  ["bezahlen", null, "v", ["to pay", "pay"], "verbs"],
  ["bestellen", null, "v", ["to order", "order"], "verbs"],
  ["packen", null, "v", ["to pack", "pack"], "verbs"],
  ["waschen", null, "v", ["to wash", "wash"], "verbs"],
  ["putzen", null, "v", ["to clean", "clean"], "verbs"],
  ["aufräumen", null, "v", ["to tidy up", "tidy up"], "verbs"],
  ["einkaufen", null, "v", ["to shop", "shop"], "verbs"],
  ["umziehen", null, "v", ["to move house", "move house"], "verbs"],
  ["besuchen", null, "v", ["to visit", "visit"], "verbs"],
  ["treffen", null, "v", ["to meet", "meet"], "verbs"],
  ["zeigen", null, "v", ["to show", "show"], "verbs"],
  ["bringen", null, "v", ["to bring", "bring"], "verbs"],
  ["holen", null, "v", ["to fetch", "fetch"], "verbs"],
  ["schicken", null, "v", ["to send", "send"], "verbs"],
  ["bekommen", null, "v", ["to receive", "get"], "verbs"],
  ["versuchen", null, "v", ["to try", "try"], "verbs"],
  ["erklären", null, "v", ["to explain", "explain"], "verbs"],
  ["vergessen", null, "v", ["to forget", "forget"], "verbs"],
  ["weinen", null, "v", ["to cry", "cry"], "verbs"],
  ["lachen", null, "v", ["to laugh", "laugh"], "verbs"],
  ["duschen", null, "v", ["to shower", "shower"], "verbs"],
  ["aufwachen", null, "v", ["to wake up", "wake up"], "verbs"],
  ["aufstehen", null, "v", ["to get up", "get up"], "verbs"],
  ["reisen", null, "v", ["to travel", "travel"], "verbs"],
  ["fotografieren", null, "v", ["to photograph", "take photos"], "verbs"],

  // More adjectives
  ["interessant", null, "adj", "interesting", "adjectives"],
  ["langweilig", null, "adj", "boring", "adjectives"],
  ["freundlich", null, "adj", "friendly", "adjectives"],
  ["nett", null, "adj", "nice", "adjectives"],
  ["lustig", null, "adj", "funny", "adjectives"],
  ["ruhig", null, "adj", "calm", "adjectives"],
  ["nervös", null, "adj", "nervous", "adjectives"],
  ["krank", null, "adj", "sick", "adjectives"],
  ["gesund", null, "adj", "healthy", "adjectives"],
  ["stark", null, "adj", "strong", "adjectives"],
  ["schwach", null, "adj", "weak", "adjectives"],
  ["hell", null, "adj", "bright", "adjectives"],
  ["dunkel", null, "adj", "dark", "adjectives"],
  ["modern", null, "adj", "modern", "adjectives"],
  ["bequem", null, "adj", "comfortable", "adjectives"],
  ["frei", null, "adj", "free", "adjectives"],
  ["sicher", null, "adj", "safe", "adjectives"],
  ["gefährlich", null, "adj", "dangerous", "adjectives"],
  ["einfach", null, "adj", "simple", "adjectives"],
  ["kompliziert", null, "adj", "complicated", "adjectives"],
  ["gleich", null, "adj", "same", "adjectives"],
  ["fertig", null, "adj", "finished", "adjectives"],
  ["kaputt", null, "adj", "broken", "adjectives"],
  ["frisch", null, "adj", "fresh", "adjectives"],

  // Animals
  ["Hund", "der", "n", "dog", "animals"],
  ["Katze", "die", "n", "cat", "animals"],
  ["Vogel", "der", "n", "bird", "animals"],
  ["Pferd", "das", "n", "horse", "animals"],
  ["Kuh", "die", "n", "cow", "animals"],
  ["Schwein", "das", "n", "pig", "animals"],
  ["Huhn", "das", "n", "chicken", "animals"],
  ["Maus", "die", "n", "mouse", "animals"],

  // Hobbies & leisure
  ["Sport", "der", "n", "sport", "hobbies"],
  ["Fußball", "der", "n", ["football", "soccer"], "hobbies"],
  ["Kino", "das", "n", "cinema", "hobbies"],
  ["Theater", "das", "n", "theatre", "hobbies"],
  ["Ferien", "die", "n", "school holidays", "hobbies"],
  ["Urlaub", "der", "n", "vacation", "hobbies"],
  ["Reise", "die", "n", "trip", "hobbies"],
  ["Hobby", "das", "n", "hobby", "hobbies"],
  ["schwimmen", null, "v", ["to swim", "swim"], "hobbies"],
  ["malen", null, "v", ["to paint", "paint"], "hobbies"],

  // More house/rooms
  ["Toilette", "die", "n", "toilet", "house"],
  ["Garten", "der", "n", "garden", "house"],
  ["Keller", "der", "n", "cellar", "house"],
  ["Balkon", "der", "n", "balcony", "house"],
  ["Garage", "die", "n", "garage", "house"],
  ["Treppe", "die", "n", "stairs", "house"],
  ["Dach", "das", "n", "roof", "house"],

  // More clothing
  ["Socken", "die", "n", "socks", "clothing"],
  ["Handschuhe", "die", "n", "gloves", "clothing"],
  ["Schal", "der", "n", "scarf", "clothing"],
  ["Gürtel", "der", "n", "belt", "clothing"],
  ["Brille", "die", "n", "glasses", "clothing"],
  ["Pullover", "der", "n", "sweater", "clothing"],

  // More body
  ["Zahn", "der", "n", "tooth", "body"],
  ["Finger", "der", "n", "finger", "body"],
  ["Herz", "das", "n", "heart", "body"],
  ["Haut", "die", "n", "skin", "body"],
  ["Knie", "das", "n", "knee", "body"],

  // More transport
  ["Motorrad", "das", "n", "motorcycle", "transport"],
  ["Straßenbahn", "die", "n", "tram", "transport"],
  ["Fahrkarte", "die", "n", "ticket", "transport"],
  ["Haltestelle", "die", "n", ["bus stop", "stop"], "transport"],
  ["Gleis", "das", "n", ["platform", "track"], "transport"],

  // More places
  ["Post", "die", "n", "post office", "places"],
  ["Bank", "die", "n", "bank", "places"],
  ["Apotheke", "die", "n", "pharmacy", "places"],
  ["Tankstelle", "die", "n", "gas station", "places"],
  ["Friseur", "der", "n", "hairdresser", "places"],
  ["Zoo", "der", "n", "zoo", "places"],
  ["Strand", "der", "n", "beach", "places"],
  ["Berg", "der", "n", "mountain", "places"],
  ["Wald", "der", "n", "forest", "places"],
  ["See", "der", "n", "lake", "places"],
  ["Fluss", "der", "n", "river", "places"],
  ["Meer", "das", "n", "sea", "places"],

  // More everyday things
  ["Idee", "die", "n", "idea", "misc"],
  ["Frage", "die", "n", "question", "misc"],
  ["Antwort", "die", "n", "answer", "misc"],
  ["Problem", "das", "n", "problem", "misc"],
  ["Grund", "der", "n", "reason", "misc"],
  ["Beispiel", "das", "n", "example", "misc"],
  ["Nachricht", "die", "n", "message", "misc"],
  ["Brief", "der", "n", "letter", "misc"],
  ["E-Mail", "die", "n", "email", "misc"],
  ["Internet", "das", "n", "internet", "misc"],
  ["Passwort", "das", "n", "password", "misc"],
  ["Rechnung", "die", "n", ["bill", "invoice"], "misc"],
  ["Preis", "der", "n", "price", "misc"],
  ["Farbe", "die", "n", "color", "misc"],
  ["Plan", "der", "n", "plan", "misc"],

  // More food & drink
  ["Butter", "die", "n", "butter", "food"],
  ["Honig", "der", "n", "honey", "food"],
  ["Marmelade", "die", "n", "jam", "food"],
  ["Nudeln", "die", "n", ["pasta", "noodles"], "food"],
  ["Pizza", "die", "n", "pizza", "food"],
  ["Salat", "der", "n", "salad", "food"],
  ["Pfeffer", "der", "n", "pepper", "food"],
  ["Obst", "das", "n", "fruit", "food"],
  ["Orange", "die", "n", "orange", "food"],
  ["Zitrone", "die", "n", "lemon", "food"],
  ["Erdbeere", "die", "n", "strawberry", "food"],
  ["Tomate", "die", "n", "tomato", "food"],
  ["Zwiebel", "die", "n", "onion", "food"],
  ["Karotte", "die", "n", "carrot", "food"],
  ["Gurke", "die", "n", "cucumber", "food"],
  ["Traube", "die", "n", "grape", "food"],
  ["Nachtisch", "der", "n", "dessert", "food"],
  ["Gewürz", "das", "n", "spice", "food"],
];

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const WORDS = RAW.map((r) => ({
  id: `${r[2]}-${slugify(r[0])}`, // stable id: part-of-speech + slugified word, not array position
  de: r[0],
  article: r[1],
  pos: r[2],
  en: Array.isArray(r[3]) ? r[3] : [r[3]],
  cat: r[4],
}));

const WORD_BY_ID = Object.fromEntries(WORDS.map((w) => [w.id, w]));

const CAT_LABELS = {
  greetings: "Greetings",
  pronouns: "Pronouns",
  questions: "Question words",
  numbers: "Numbers",
  colors: "Colors",
  family: "Family",
  food: "Food & drink",
  time: "Time & calendar",
  weather: "Weather",
  body: "Body",
  clothing: "Clothing",
  house: "House",
  places: "Places",
  transport: "Transport",
  verbs: "Verbs",
  adjectives: "Adjectives",
  grammar: "Prepositions & conjunctions",
  misc: "Everyday things",
  directions: "Directions",
  adverbs: "Adverbs & quantifiers",
  animals: "Animals",
  hobbies: "Hobbies & leisure",
};
