/* ----------------------------------------------------------------------
   A1 GERMAN VOCABULARY DATA
   [de, article|null, pos, en(string|array), category]
------------------------------------------------------------------------*/
const RAW = [
  // Greetings & phrases
  ["Hallo", null, "phrase", "hello", "greetings"],
  ["Guten Morgen", null, "phrase", "good morning", "greetings"],
  ["Guten Tag", null, "phrase", "good day", "greetings"],
  ["Guten Abend", null, "phrase", "good evening", "greetings"],
  ["Gute Nacht", null, "phrase", "good night", "greetings"],
  ["Auf Wiedersehen", null, "phrase", "goodbye", "greetings"],
  ["Tschüss", null, "phrase", "bye", "greetings"],
  ["Bis bald", null, "phrase", "see you soon", "greetings"],
  ["Bitte", null, "phrase", ["please", "you're welcome"], "greetings"],
  ["Danke", null, "phrase", "thank you", "greetings"],
  ["Entschuldigung", null, "phrase", ["excuse me", "sorry"], "greetings"],
  ["Ja", null, "phrase", "yes", "greetings"],
  ["Nein", null, "phrase", "no", "greetings"],
  ["Vielleicht", null, "adv", "maybe", "greetings"],
  ["Wie geht es dir", null, "phrase", "how are you", "greetings"],
  ["Mir geht es gut", null, "phrase", "I'm fine", "greetings"],
  ["Willkommen", null, "phrase", "welcome", "greetings"],

  // Pronouns
  ["ich", null, "pron", "I", "pronouns"],
  ["du", null, "pron", "you", "pronouns"],
  ["er", null, "pron", "he", "pronouns"],
  ["sie", null, "pron", "she", "pronouns"],
  ["es", null, "pron", "it", "pronouns"],
  ["wir", null, "pron", "we", "pronouns"],
  ["ihr", null, "pron", "you (plural)", "pronouns"],
  ["mein", null, "pron", "my", "pronouns"],
  ["dein", null, "pron", "your", "pronouns"],
  ["sein", null, "pron", "his", "pronouns"],
  ["unser", null, "pron", "our", "pronouns"],

  // Question words
  ["wer", null, "pron", "who", "questions"],
  ["was", null, "pron", "what", "questions"],
  ["wo", null, "adv", "where", "questions"],
  ["wann", null, "adv", "when", "questions"],
  ["warum", null, "adv", "why", "questions"],
  ["wie", null, "adv", "how", "questions"],
  ["welche", null, "pron", "which", "questions"],

  // Numbers
  ["null", null, "num", "zero", "numbers"],
  ["eins", null, "num", "one", "numbers"],
  ["zwei", null, "num", "two", "numbers"],
  ["drei", null, "num", "three", "numbers"],
  ["vier", null, "num", "four", "numbers"],
  ["fünf", null, "num", "five", "numbers"],
  ["sechs", null, "num", "six", "numbers"],
  ["sieben", null, "num", "seven", "numbers"],
  ["acht", null, "num", "eight", "numbers"],
  ["neun", null, "num", "nine", "numbers"],
  ["zehn", null, "num", "ten", "numbers"],
  ["elf", null, "num", "eleven", "numbers"],
  ["zwölf", null, "num", "twelve", "numbers"],
  ["dreizehn", null, "num", "thirteen", "numbers"],
  ["vierzehn", null, "num", "fourteen", "numbers"],
  ["fünfzehn", null, "num", "fifteen", "numbers"],
  ["zwanzig", null, "num", "twenty", "numbers"],
  ["dreißig", null, "num", "thirty", "numbers"],
  ["vierzig", null, "num", "forty", "numbers"],
  ["fünfzig", null, "num", "fifty", "numbers"],
  ["hundert", null, "num", "hundred", "numbers"],
  ["tausend", null, "num", "thousand", "numbers"],

  // Colors
  ["rot", null, "adj", "red", "colors"],
  ["blau", null, "adj", "blue", "colors"],
  ["gelb", null, "adj", "yellow", "colors"],
  ["grün", null, "adj", "green", "colors"],
  ["schwarz", null, "adj", "black", "colors"],
  ["weiß", null, "adj", "white", "colors"],
  ["braun", null, "adj", "brown", "colors"],
  ["orange", null, "adj", "orange", "colors"],
  ["rosa", null, "adj", "pink", "colors"],
  ["grau", null, "adj", "grey", "colors"],
  ["lila", null, "adj", "purple", "colors"],

  // Family
  ["Familie", "die", "n", "family", "family"],
  ["Mutter", "die", "n", "mother", "family"],
  ["Vater", "der", "n", "father", "family"],
  ["Schwester", "die", "n", "sister", "family"],
  ["Bruder", "der", "n", "brother", "family"],
  ["Tochter", "die", "n", "daughter", "family"],
  ["Sohn", "der", "n", "son", "family"],
  ["Großmutter", "die", "n", "grandmother", "family"],
  ["Großvater", "der", "n", "grandfather", "family"],
  ["Frau", "die", "n", ["woman", "wife"], "family"],
  ["Mann", "der", "n", ["man", "husband"], "family"],
  ["Kind", "das", "n", "child", "family"],
  ["Eltern", "die", "n", "parents", "family"],
  ["Tante", "die", "n", "aunt", "family"],
  ["Onkel", "der", "n", "uncle", "family"],
  ["Freund", "der", "n", ["friend", "boyfriend"], "family"],
  ["Freundin", "die", "n", ["friend", "girlfriend"], "family"],

  // Food & drink
  ["Brot", "das", "n", "bread", "food"],
  ["Käse", "der", "n", "cheese", "food"],
  ["Milch", "die", "n", "milk", "food"],
  ["Wasser", "das", "n", "water", "food"],
  ["Kaffee", "der", "n", "coffee", "food"],
  ["Tee", "der", "n", "tea", "food"],
  ["Apfel", "der", "n", "apple", "food"],
  ["Banane", "die", "n", "banana", "food"],
  ["Ei", "das", "n", "egg", "food"],
  ["Zucker", "der", "n", "sugar", "food"],
  ["Salz", "das", "n", "salt", "food"],
  ["Suppe", "die", "n", "soup", "food"],
  ["Fleisch", "das", "n", "meat", "food"],
  ["Fisch", "der", "n", "fish", "food"],
  ["Gemüse", "das", "n", "vegetables", "food"],
  ["Reis", "der", "n", "rice", "food"],
  ["Kartoffel", "die", "n", "potato", "food"],
  ["Saft", "der", "n", "juice", "food"],
  ["Wein", "der", "n", "wine", "food"],
  ["Bier", "das", "n", "beer", "food"],
  ["Frühstück", "das", "n", "breakfast", "food"],
  ["Mittagessen", "das", "n", "lunch", "food"],
  ["Abendessen", "das", "n", "dinner", "food"],
  ["Kuchen", "der", "n", "cake", "food"],
  ["Schokolade", "die", "n", "chocolate", "food"],

  // Time & calendar
  ["Zeit", "die", "n", "time", "time"],
  ["Stunde", "die", "n", "hour", "time"],
  ["Minute", "die", "n", "minute", "time"],
  ["Tag", "der", "n", "day", "time"],
  ["Woche", "die", "n", "week", "time"],
  ["Monat", "der", "n", "month", "time"],
  ["Jahr", "das", "n", "year", "time"],
  ["heute", null, "adv", "today", "time"],
  ["morgen", null, "adv", "tomorrow", "time"],
  ["gestern", null, "adv", "yesterday", "time"],
  ["Montag", "der", "n", "Monday", "time"],
  ["Dienstag", "der", "n", "Tuesday", "time"],
  ["Mittwoch", "der", "n", "Wednesday", "time"],
  ["Donnerstag", "der", "n", "Thursday", "time"],
  ["Freitag", "der", "n", "Friday", "time"],
  ["Samstag", "der", "n", "Saturday", "time"],
  ["Sonntag", "der", "n", "Sunday", "time"],
  ["Januar", "der", "n", "January", "time"],
  ["Februar", "der", "n", "February", "time"],
  ["März", "der", "n", "March", "time"],
  ["April", "der", "n", "April", "time"],
  ["Mai", "der", "n", "May", "time"],
  ["Juni", "der", "n", "June", "time"],
  ["Juli", "der", "n", "July", "time"],
  ["August", "der", "n", "August", "time"],
  ["September", "der", "n", "September", "time"],
  ["Oktober", "der", "n", "October", "time"],
  ["November", "der", "n", "November", "time"],
  ["Dezember", "der", "n", "December", "time"],
  ["Frühling", "der", "n", "spring", "time"],
  ["Sommer", "der", "n", "summer", "time"],
  ["Herbst", "der", "n", "autumn", "time"],
  ["Winter", "der", "n", "winter", "time"],

  // Weather
  ["Wetter", "das", "n", "weather", "weather"],
  ["Sonne", "die", "n", "sun", "weather"],
  ["Regen", "der", "n", "rain", "weather"],
  ["Schnee", "der", "n", "snow", "weather"],
  ["Wind", "der", "n", "wind", "weather"],
  ["warm", null, "adj", "warm", "weather"],
  ["kalt", null, "adj", "cold", "weather"],
  ["heiß", null, "adj", "hot", "weather"],
  ["kühl", null, "adj", "cool", "weather"],

  // Body
  ["Kopf", "der", "n", "head", "body"],
  ["Auge", "das", "n", "eye", "body"],
  ["Nase", "die", "n", "nose", "body"],
  ["Mund", "der", "n", "mouth", "body"],
  ["Ohr", "das", "n", "ear", "body"],
  ["Hand", "die", "n", "hand", "body"],
  ["Fuß", "der", "n", "foot", "body"],
  ["Arm", "der", "n", "arm", "body"],
  ["Bein", "das", "n", "leg", "body"],
  ["Bauch", "der", "n", "stomach", "body"],
  ["Haar", "das", "n", "hair", "body"],
  ["Rücken", "der", "n", "back", "body"],

  // Clothing
  ["Kleidung", "die", "n", "clothing", "clothing"],
  ["Hemd", "das", "n", "shirt", "clothing"],
  ["Hose", "die", "n", "trousers", "clothing"],
  ["Rock", "der", "n", "skirt", "clothing"],
  ["Kleid", "das", "n", "dress", "clothing"],
  ["Jacke", "die", "n", "jacket", "clothing"],
  ["Schuhe", "die", "n", "shoes", "clothing"],
  ["Hut", "der", "n", "hat", "clothing"],
  ["Mütze", "die", "n", "cap", "clothing"],

  // House
  ["Haus", "das", "n", "house", "house"],
  ["Wohnung", "die", "n", "apartment", "house"],
  ["Zimmer", "das", "n", "room", "house"],
  ["Küche", "die", "n", "kitchen", "house"],
  ["Bad", "das", "n", "bathroom", "house"],
  ["Schlafzimmer", "das", "n", "bedroom", "house"],
  ["Wohnzimmer", "das", "n", "living room", "house"],
  ["Tisch", "der", "n", "table", "house"],
  ["Stuhl", "der", "n", "chair", "house"],
  ["Bett", "das", "n", "bed", "house"],
  ["Tür", "die", "n", "door", "house"],
  ["Fenster", "das", "n", "window", "house"],
  ["Wand", "die", "n", "wall", "house"],
  ["Boden", "der", "n", "floor", "house"],
  ["Lampe", "die", "n", "lamp", "house"],

  // Places
  ["Stadt", "die", "n", "city", "places"],
  ["Dorf", "das", "n", "village", "places"],
  ["Straße", "die", "n", "street", "places"],
  ["Park", "der", "n", "park", "places"],
  ["Schule", "die", "n", "school", "places"],
  ["Universität", "die", "n", "university", "places"],
  ["Krankenhaus", "das", "n", "hospital", "places"],
  ["Bahnhof", "der", "n", "train station", "places"],
  ["Flughafen", "der", "n", "airport", "places"],
  ["Geschäft", "das", "n", "shop", "places"],
  ["Supermarkt", "der", "n", "supermarket", "places"],
  ["Restaurant", "das", "n", "restaurant", "places"],
  ["Hotel", "das", "n", "hotel", "places"],
  ["Kirche", "die", "n", "church", "places"],
  ["Bibliothek", "die", "n", "library", "places"],
  ["Büro", "das", "n", "office", "places"],
  ["Markt", "der", "n", "market", "places"],

  // Transport
  ["Auto", "das", "n", "car", "transport"],
  ["Bus", "der", "n", "bus", "transport"],
  ["Zug", "der", "n", "train", "transport"],
  ["Fahrrad", "das", "n", "bicycle", "transport"],
  ["Flugzeug", "das", "n", "airplane", "transport"],
  ["Schiff", "das", "n", "ship", "transport"],
  ["U-Bahn", "die", "n", "subway", "transport"],
  ["Taxi", "das", "n", "taxi", "transport"],

  // Verbs
  ["sein", null, "v", ["to be", "be"], "verbs"],
  ["haben", null, "v", ["to have", "have"], "verbs"],
  ["werden", null, "v", ["to become", "become"], "verbs"],
  ["gehen", null, "v", ["to go", "go"], "verbs"],
  ["kommen", null, "v", ["to come", "come"], "verbs"],
  ["machen", null, "v", ["to make", "to do", "do"], "verbs"],
  ["sagen", null, "v", ["to say", "say"], "verbs"],
  ["sehen", null, "v", ["to see", "see"], "verbs"],
  ["wissen", null, "v", ["to know", "know"], "verbs"],
  ["geben", null, "v", ["to give", "give"], "verbs"],
  ["nehmen", null, "v", ["to take", "take"], "verbs"],
  ["finden", null, "v", ["to find", "find"], "verbs"],
  ["denken", null, "v", ["to think", "think"], "verbs"],
  ["bleiben", null, "v", ["to stay", "stay"], "verbs"],
  ["liegen", null, "v", ["to lie", "lie down"], "verbs"],
  ["sitzen", null, "v", ["to sit", "sit"], "verbs"],
  ["stehen", null, "v", ["to stand", "stand"], "verbs"],
  ["arbeiten", null, "v", ["to work", "work"], "verbs"],
  ["spielen", null, "v", ["to play", "play"], "verbs"],
  ["lernen", null, "v", ["to learn", "learn"], "verbs"],
  ["essen", null, "v", ["to eat", "eat"], "verbs"],
  ["trinken", null, "v", ["to drink", "drink"], "verbs"],
  ["schlafen", null, "v", ["to sleep", "sleep"], "verbs"],
  ["leben", null, "v", ["to live", "live"], "verbs"],
  ["lieben", null, "v", ["to love", "love"], "verbs"],
  ["mögen", null, "v", ["to like", "like"], "verbs"],
  ["brauchen", null, "v", ["to need", "need"], "verbs"],
  ["kaufen", null, "v", ["to buy", "buy"], "verbs"],
  ["verkaufen", null, "v", ["to sell", "sell"], "verbs"],
  ["kochen", null, "v", ["to cook", "cook"], "verbs"],
  ["lesen", null, "v", ["to read", "read"], "verbs"],
  ["schreiben", null, "v", ["to write", "write"], "verbs"],
  ["sprechen", null, "v", ["to speak", "speak"], "verbs"],
  ["hören", null, "v", ["to hear", "to listen", "listen"], "verbs"],
  ["fragen", null, "v", ["to ask", "ask"], "verbs"],
  ["antworten", null, "v", ["to answer", "answer"], "verbs"],
  ["helfen", null, "v", ["to help", "help"], "verbs"],
  ["verstehen", null, "v", ["to understand", "understand"], "verbs"],
  ["fahren", null, "v", ["to drive", "to go (by vehicle)", "drive"], "verbs"],
  ["fliegen", null, "v", ["to fly", "fly"], "verbs"],
  ["laufen", null, "v", ["to run", "to walk", "run"], "verbs"],
  ["tanzen", null, "v", ["to dance", "dance"], "verbs"],
  ["singen", null, "v", ["to sing", "sing"], "verbs"],
  ["kennen", null, "v", ["to know", "to be familiar with", "know"], "verbs"],
  ["wohnen", null, "v", ["to live", "to reside", "reside"], "verbs"],
  ["heißen", null, "v", ["to be called", "be named"], "verbs"],
  ["öffnen", null, "v", ["to open", "open"], "verbs"],
  ["schließen", null, "v", ["to close", "close"], "verbs"],
  ["warten", null, "v", ["to wait", "wait"], "verbs"],

  // Adjectives
  ["groß", null, "adj", ["big", "tall"], "adjectives"],
  ["klein", null, "adj", "small", "adjectives"],
  ["gut", null, "adj", "good", "adjectives"],
  ["schlecht", null, "adj", "bad", "adjectives"],
  ["neu", null, "adj", "new", "adjectives"],
  ["alt", null, "adj", "old", "adjectives"],
  ["jung", null, "adj", "young", "adjectives"],
  ["schön", null, "adj", ["beautiful", "nice"], "adjectives"],
  ["hässlich", null, "adj", "ugly", "adjectives"],
  ["schnell", null, "adj", "fast", "adjectives"],
  ["langsam", null, "adj", "slow", "adjectives"],
  ["leicht", null, "adj", ["easy", "light"], "adjectives"],
  ["schwer", null, "adj", ["difficult", "heavy"], "adjectives"],
  ["teuer", null, "adj", "expensive", "adjectives"],
  ["billig", null, "adj", "cheap", "adjectives"],
  ["glücklich", null, "adj", "happy", "adjectives"],
  ["traurig", null, "adj", "sad", "adjectives"],
  ["müde", null, "adj", "tired", "adjectives"],
  ["hungrig", null, "adj", "hungry", "adjectives"],
  ["durstig", null, "adj", "thirsty", "adjectives"],
  ["sauber", null, "adj", "clean", "adjectives"],
  ["schmutzig", null, "adj", "dirty", "adjectives"],
  ["laut", null, "adj", "loud", "adjectives"],
  ["leise", null, "adj", "quiet", "adjectives"],
  ["wichtig", null, "adj", "important", "adjectives"],
  ["richtig", null, "adj", "correct", "adjectives"],
  ["falsch", null, "adj", "wrong", "adjectives"],
  ["voll", null, "adj", "full", "adjectives"],
  ["leer", null, "adj", "empty", "adjectives"],
  ["offen", null, "adj", "open", "adjectives"],
  ["geschlossen", null, "adj", "closed", "adjectives"],

  // Prepositions & conjunctions
  ["in", null, "prep", "in", "grammar"],
  ["auf", null, "prep", "on", "grammar"],
  ["unter", null, "prep", "under", "grammar"],
  ["über", null, "prep", "over", "grammar"],
  ["neben", null, "prep", "next to", "grammar"],
  ["vor", null, "prep", ["in front of", "before"], "grammar"],
  ["hinter", null, "prep", "behind", "grammar"],
  ["zwischen", null, "prep", "between", "grammar"],
  ["mit", null, "prep", "with", "grammar"],
  ["ohne", null, "prep", "without", "grammar"],
  ["für", null, "prep", "for", "grammar"],
  ["gegen", null, "prep", "against", "grammar"],
  ["und", null, "conj", "and", "grammar"],
  ["oder", null, "conj", "or", "grammar"],
  ["aber", null, "conj", "but", "grammar"],
  ["weil", null, "conj", "because", "grammar"],
  ["dass", null, "conj", "that", "grammar"],
  ["wenn", null, "conj", "if", "grammar"],

  // Misc nouns
  ["Name", "der", "n", "name", "misc"],
  ["Adresse", "die", "n", "address", "misc"],
  ["Telefonnummer", "die", "n", "phone number", "misc"],
  ["Arbeit", "die", "n", "work", "misc"],
  ["Beruf", "der", "n", "job", "misc"],
  ["Geld", "das", "n", "money", "misc"],
  ["Zeitung", "die", "n", "newspaper", "misc"],
  ["Buch", "das", "n", "book", "misc"],
  ["Stift", "der", "n", "pen", "misc"],
  ["Papier", "das", "n", "paper", "misc"],
  ["Tasche", "die", "n", "bag", "misc"],
  ["Schlüssel", "der", "n", "key", "misc"],
  ["Handy", "das", "n", "mobile phone", "misc"],
  ["Computer", "der", "n", "computer", "misc"],
  ["Foto", "das", "n", "photo", "misc"],
  ["Musik", "die", "n", "music", "misc"],
  ["Film", "der", "n", "film", "misc"],
  ["Spiel", "das", "n", "game", "misc"],
  ["Sprache", "die", "n", "language", "misc"],
  ["Welt", "die", "n", "world", "misc"],
];

const WORDS = RAW.map((r, i) => ({
  id: "w" + i,
  de: r[0],
  article: r[1],
  pos: r[2],
  en: Array.isArray(r[3]) ? r[3] : [r[3]],
  cat: r[4],
}));

const WORD_BY_ID = Object.fromEntries(WORDS.map((w) => [w.id, w]));

const CAT_LABELS = {
  greetings: "Greetings",
  pronouns: "Pronouns",
  questions: "Question words",
  numbers: "Numbers",
  colors: "Colors",
  family: "Family",
  food: "Food & drink",
  time: "Time & calendar",
  weather: "Weather",
  body: "Body",
  clothing: "Clothing",
  house: "House",
  places: "Places",
  transport: "Transport",
  verbs: "Verbs",
  adjectives: "Adjectives",
  grammar: "Prepositions & conjunctions",
  misc: "Everyday things",
};
